Implement scheduling_endpoint attribute
Icinga/icinga2 pull request #6326
Opened 2018-05-22 19:35 UTC by mcktr

This implements the attribute `scheduling_endpoint` for hosts and services to show which endpoint is running the scheduler for the check.

refs #4814

2018-05-23 08:19 UTC, dnsmichi commented
Thx. Put on hold for now, I'll review after 2.9.

There's schema and backend changes which involve a couple of other projects @lippserd.

2018-07-03 09:34 UTC, dnsmichi commented
Probably `scheduling_source` or similar would better fit the terminology. I'll look further when 2.10 is near.

2018-07-03 17:15 UTC, mcktr commented
Yepp, `scheduling_source` sounds more suitable. I'll update the PR when I find a bit time (probably next week).

2018-08-01 18:43 UTC, mcktr commented
I updated the PR to use the better fitting name.

2019-02-11 15:38 UTC, dnsmichi commented
@lippserd this is relevant for IcingaDB, please decide on a final name here :)

2019-11-14 12:05 UTC, dnsmichi commented
@Al2Klimov @N-o-X please discuss this with @lippserd whether it is relevant for the 2.12 RC and IcingaDB.

2019-11-14 15:48 UTC, Al2Klimov commented
AFAIK we've already implemented all needed attributes for IcingaDB.

2020-03-26 14:09 UTC, Al2Klimov commented on lib/icinga/checkresult.ti
> +	[state] String scheduling_source;
Don't you need to sync this one across the cluster?

2020-03-26 14:14 UTC, Al2Klimov commented on lib/icinga/checkresult.ti
> +	[state] String scheduling_source;
Forget that question, check_source isn't explicitly synced either.

2020-03-26 19:03 UTC, mcktr commented
`scheduling_source` indicates which node is responsible for scheduling the checks, to made this information available for Icinga Web 2

# Test

- master
- agent

```
# /etc/icinga2/zones.d/master/test.conf

object Host "host-scheduled-on-master" {
	address = "172.17.0.2"

	check_command = "random"

	check_interval = 30s
	retry_interval = 10s
	max_check_attempts = 3
}

object Service "service-scheduled-on-master" {
	check_command = "random"

	command_endpoint = "deb10i2b1"

	check_interval = 10s
	retry_interval = 5s
	max_check_attempts = 5

	host_name = "host-scheduled-on-master"
}
```

Querying the API: 

```
{
  "attrs": {
    "__name": "host-scheduled-on-master!service-scheduled-on-master",
    [...]
    "check_source": "deb10i2b1",
    [...]
    "scheduling_source": "metis",
    [...]
}
```

2020-04-07 14:08 UTC, lippserd commented
@N-o-X or @Al2Klimov Please don't forget to create a follow up issue for Icinga DB. And this PR should also add docs since this is also exposed in our API, right?

2021-07-16 09:11 UTC, nilmerg commented
@mcktr Any chance that you'll add documentation for this until next monday? I know, short notice, but I'd like to have this included in 2.13 and not post-poned just because a doc update is missing. If you don't have time for this, comment or give me a thumbs-down, then we'll do the doc update. (I'll do it if required, but I'd welcome you doing it, as I don't know much about this or Icinga 2 documentation to begin with :sweat_smile: )

2021-07-18 20:31 UTC, mcktr commented
@nilmerg I added the missing documentation for the `scheduling_source` attribute. I also rebased this PR against the `master` branch and resolved all merge conflicts. 

Best regards
Michael

2021-07-20 08:59 UTC, Al2Klimov requested changes
One last thing:

Please squash the commits and adjust the attribute name in the commit message.

2021-07-20 09:10 UTC, merged