WIP: Change the order of the object sync
Icinga/icinga2 pull request #7786
Opened 2020-01-27 15:00 UTC by htriem

2021-09-09 10:16 UTC, julianbrost commented
@htriem Please either state the purpose of the PR or close it if you don't consider it important (anymore).

2023-01-20 11:33 UTC, Al2Klimov reviewed
Concept looks good, rebase it against master.

2023-01-20 12:52 UTC, julianbrost commented
What's the purpose of the change? Does it fix a bug? Is it a performance improvement?

2023-01-20 13:56 UTC, Al2Klimov commented
If there's a bug, it fixes it at the cost of performance. It re-orders runtime updates for pretty much the same reasons as we order objects while loading config initially. Once Henrik rebased this and there's something to test I maybe find a way to provoke the bug if any.

2023-01-20 14:23 UTC, julianbrost commented
I don't really understand. There must be a reason why this PR was created and you must have had a reason why you consider it a good concept.

2023-01-20 14:29 UTC, Al2Klimov commented
Damn, the reason I had in mind has been removed by 28c29c1fbc6cd6239390eaf9663b0242c000af9c. For now feel free to consider it a just-to-be-sure.

2023-01-24 11:12 UTC, htriem commented
Rebased it on top of the master.

2023-01-24 11:34 UTC, julianbrost commented
> For now feel free to consider it a just-to-be-sure.

So the purpose is to increase the robustness of the object config sync?

I've looked at the change, and one situation where I can imagine this might help would be that while a child node is offline, a host and service are created for example. If the child node reconnect, could it happen without that change that the service is sent first and then fails to load? But haven't tried any of this, just wild guessing from looking at the code.

But really, if there's a proposed change, there should be a description with a motivation for the change. It shouldn't need someone else looking at the code and guessing the purpose.

2023-01-24 11:38 UTC, Al2Klimov commented
That was also my guess, but I wanted to first test it once there is something to test. Apropos...

2023-01-24 11:38 UTC, Al2Klimov requested changes
Pipelines fail

2023-01-24 11:51 UTC, julianbrost commented
Wouldn't you test if something is broken on master or a release? So that can be done before anyone puts effort into updating an old PR.

2023-01-30 11:39 UTC, Al2Klimov commented
> Damn, the reason I had in mind has been removed by [28c29c1](https://github.com/Icinga/icinga2/commit/28c29c1fbc6cd6239390eaf9663b0242c000af9c)

Hence:

> @htriem Please either state the purpose of the PR

2023-10-09 15:42 UTC, Al2Klimov commented
@julianbrost OK, now I have enough information to give you an answer:

#9752 shouldn't happen, right? But it happens – a comment's host is missing. I thought, maybe the host is only missing _yet_. Maybe it should just get send over the wire before the comment itself, hence this PR. But https://github.com/Icinga/icinga2/pull/9873#issuecomment-1753228926 says no.

2025-01-07 12:32 UTC, closed without merging