Doc: clarify TimePeriod/ScheduledDowntime time zone handling
Icinga/icinga2 pull request #8001
Opened 2020-05-12 10:55 UTC by Al2Klimov

fixes #7069

2020-12-03 14:54 UTC, julianbrost reviewed
The change itself is fine but I wouldn't say that this alone fixes #7069. For example, it does not explain what exactly happens, if a DST change happens within an interval. Other questions that might be interesting and I can't answer from the docs: what happens if the start or end is something like 2:30 on a DST change day and this time either exists twice or not at all?

2020-12-14 11:53 UTC, Al2Klimov commented
In you opinion: Shall we really promise anything e.g. regarding start/end at the twice appearing (i.e. ambiguous) 2020-10-25T02:30:00?

2020-12-14 11:58 UTC, Al2Klimov commented
Or – even better – at 2020-03-29T02:30:00 which doesn't exist at all?

2020-12-16 10:29 UTC, julianbrost commented
Well, something has to happen if you specify this in the config. I don't think it's a good idea to leave it as a surprise what happens exactly. [The docs even use 2:00-3:00 in examples](https://icinga.com/docs/icinga-2/latest/doc/08-advanced-topics/#recurring-downtimes), what will happen on days with DST changes?

2021-01-12 11:19 UTC, Al2Klimov commented
Do you think the surprise is a bad idea due to our examples and the fact that we don’t advise against such or in general?

2021-01-13 15:36 UTC, julianbrost commented
I'm fine with this PR, but it should not have "fixes #7069" as I think we can do better than this.

What we should do in my opinion to actually fix that issue is to take a look at the current behavior including all kinds of nasty edge cases and depending on whether it makes sense, document it as is or fix the implementation and then document it.

2021-01-14 12:10 UTC, Al2Klimov commented
## CEST -> CET: CEST

```
➜  icinga2 git:(master) cat 8001/etc/icinga2/conf.d/8001.conf
apply ScheduledDowntime "8001" to Host {
	author = "me"
	comment = " "
	ranges = { sunday = "2:15-2:45" }
	assign where true
}
➜  icinga2 git:(master) docker run --rm -itv $(pwd)/8001:/data -e LD_PRELOAD=/data/libfaketime/src/libfaketime.so.1 -e FAKETIME=-82d -e TZ=Europe/Berlin icinga/icinga2:master date
[2021-01-14 12:39:42 +0100] information/DockerEntrypoint: Initializing /data as we're the init process (PID 1)
[2021-01-14 12:39:42 +0100] information/DockerEntrypoint: Checking "/data/etc/icinga2"
[2021-01-14 12:39:42 +0100] information/DockerEntrypoint: Checking "/data/var/cache/icinga2"
[2021-01-14 12:39:42 +0100] information/DockerEntrypoint: Checking "/data/var/lib/icinga2"
[2021-01-14 12:39:42 +0100] information/DockerEntrypoint: Checking "/data/var/log/icinga2"
[2021-01-14 12:39:42 +0100] information/DockerEntrypoint: Checking "/data/var/run/icinga2"
[2021-01-14 12:39:42 +0100] information/DockerEntrypoint: Checking "/data/var/spool/icinga2"
[2021-01-14 12:39:42 +0100] information/DockerEntrypoint: Checking "/var/lib/icinga2/certs/ca.crt"
[2021-01-14 12:39:42 +0100] information/DockerEntrypoint: Looking up "dumb-init" in $PATH
[2021-01-14 12:39:42 +0100] information/DockerEntrypoint: Running "/usr/bin/dumb-init"
Sat Oct 24 13:39:42 CEST 2020
➜  icinga2 git:(master) docker run --rm -itv $(pwd)/8001:/data -e LD_PRELOAD=/data/libfaketime/src/libfaketime.so.1 -e FAKETIME=-82d -e TZ=Europe/Berlin icinga/icinga2:master
[2021-01-14 12:39:55 +0100] information/DockerEntrypoint: Initializing /data as we're the init process (PID 1)
[2021-01-14 12:39:55 +0100] information/DockerEntrypoint: Checking "/data/etc/icinga2"
[2021-01-14 12:39:55 +0100] information/DockerEntrypoint: Checking "/data/var/cache/icinga2"
[2021-01-14 12:39:55 +0100] information/DockerEntrypoint: Checking "/data/var/lib/icinga2"
[2021-01-14 12:39:55 +0100] information/DockerEntrypoint: Checking "/data/var/log/icinga2"
[2021-01-14 12:39:55 +0100] information/DockerEntrypoint: Checking "/data/var/run/icinga2"
[2021-01-14 12:39:55 +0100] information/DockerEntrypoint: Checking "/data/var/spool/icinga2"
[2021-01-14 12:39:55 +0100] information/DockerEntrypoint: Checking "/var/lib/icinga2/certs/ca.crt"
[2021-01-14 12:39:55 +0100] information/DockerEntrypoint: Looking up "dumb-init" in $PATH
[2021-01-14 12:39:55 +0100] information/DockerEntrypoint: Running "/usr/bin/dumb-init"
[2020-10-24 13:39:55 +0200] information/cli: Icinga application loader (version: r2.12.0-1)
[2020-10-24 13:39:55 +0200] information/cli: Loading configuration file(s).
[2020-10-24 13:39:55 +0200] information/ConfigItem: Committing config item(s).
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 1 User.
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 1 UserGroup.
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 3 ServiceGroups.
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 3 TimePeriods.
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 11 Services.
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 3 Zones.
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 2 ScheduledDowntimes.
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 2 HostGroups.
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 2 NotificationCommands.
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 12 Notifications.
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 1 Host.
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 1 Endpoint.
[2020-10-24 13:39:55 +0200] information/ConfigItem: Instantiated 235 CheckCommands.
[2020-10-24 13:39:55 +0200] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2020-10-24 13:39:55 +0200] information/ConfigObject: Restoring program state from file '/var/lib/icinga2/icinga2.state'
[2020-10-24 13:39:55 +0200] information/ConfigObject: Restored 283 objects. Loaded 28 new objects without state.
[2020-10-24 13:39:56 +0200] information/ConfigItem: Triggering Start signal for config items
[2020-10-24 13:39:56 +0200] information/NotificationComponent: 'notification' started.
[2020-10-24 13:39:56 +0200] information/CheckerComponent: 'checker' started.
[2020-10-24 13:39:56 +0200] information/ConfigItem: Activated all objects.
[2020-10-24 13:40:56 +0200] information/ConfigObjectUtility: Created and activated object 'daef7cb16335!load!b0ea7cf7-e899-4c77-a0d4-ef4c581ff5ad' of type 'Downtime'.
[2020-10-24 13:40:56 +0200] information/Downtime: Added downtime 'daef7cb16335!load!b0ea7cf7-e899-4c77-a0d4-ef4c581ff5ad' between '2020-10-25 02:00:00' and '2020-10-25 02:00:00', author: 'icingaadmin', fixed
[2020-10-24 13:40:56 +0200] information/ConfigObjectUtility: Created and activated object 'daef7cb16335!95e534ba-7f92-4bdb-896e-bd35d93b6440' of type 'Downtime'.
[2020-10-24 13:40:56 +0200] information/Downtime: Added downtime 'daef7cb16335!95e534ba-7f92-4bdb-896e-bd35d93b6440' between '2020-10-25 02:15:00' and '2020-10-25 02:45:00', author: 'me', fixed
^C[2021-01-14 12:41:08 +0100] information/Application: Received request to shut down.
[2021-01-14 12:41:08 +0100] information/Application: Received request to shut down.
[2020-10-24 13:41:08 +0200] information/Application: Shutting down...
[2020-10-24 13:41:08 +0200] information/CheckerComponent: 'checker' stopped.
[2020-10-24 13:41:08 +0200] information/NotificationComponent: 'notification' stopped.
[2020-10-24 13:41:08 +0200] information/ConfigObject: Dumping program state to file '/var/lib/icinga2/icinga2.state'
[2020-10-24 13:41:08 +0200] information/IcingaApplication: Icinga has shut down.
➜  icinga2 git:(master) find 8001 -name '*95e534ba-7f92-4bdb-896e-bd35d93b6440*'
8001/var/lib/icinga2/api/packages/_api/601a910f-4f1e-4911-b656-e85ea7787650/conf.d/downtimes/daef7cb16335!95e534ba-7f92-4bdb-896e-bd35d93b6440.conf
➜  icinga2 git:(master) cat 8001/var/lib/icinga2/api/packages/_api/601a910f-4f1e-4911-b656-e85ea7787650/conf.d/downtimes/daef7cb16335\!95e534ba-7f92-4bdb-896e-bd35d93b6440.conf
object Downtime "95e534ba-7f92-4bdb-896e-bd35d93b6440" ignore_on_error {
	author = "me"
	comment = " "
	config_owner = "daef7cb16335!8001"
	duration = 0.000000
	end_time = 1603586700.000000
	entry_time = 1603539656.069030
	fixed = true
	host_name = "daef7cb16335"
	scheduled_by = "daef7cb16335!8001"
	start_time = 1603584900.000000
	triggered_by = ""
	version = 1603539656.069074
}
➜  icinga2 git:(master) date -r 1603584900
So 25 Okt 2020 02:15:00 CEST
➜  icinga2 git:(master) date -r 1603586700
So 25 Okt 2020 02:45:00 CEST
➜  icinga2 git:(master)
```

## CET -> CEST: CET

```
➜  icinga2 git:(master) cat 8001/etc/icinga2/conf.d/8001.conf
apply ScheduledDowntime "8001" to Host {
	author = "me"
	comment = " "
	ranges = { sunday = "2:15-2:45" }
	assign where true
}
➜  icinga2 git:(master) docker run --rm -itv $(pwd)/8001:/data -e LD_PRELOAD=/data/libfaketime/src/libfaketime.so.1 -e FAKETIME=+72d -e TZ=Europe/Berlin icinga/icinga2:master date
[2021-01-14 13:01:15 +0100] information/DockerEntrypoint: Initializing /data as we're the init process (PID 1)
[2021-01-14 13:01:15 +0100] information/DockerEntrypoint: Checking "/data/etc/icinga2"
[2021-01-14 13:01:15 +0100] information/DockerEntrypoint: Checking "/data/var/cache/icinga2"
[2021-01-14 13:01:15 +0100] information/DockerEntrypoint: Checking "/data/var/lib/icinga2"
[2021-01-14 13:01:15 +0100] information/DockerEntrypoint: Checking "/data/var/log/icinga2"
[2021-01-14 13:01:15 +0100] information/DockerEntrypoint: Checking "/data/var/run/icinga2"
[2021-01-14 13:01:15 +0100] information/DockerEntrypoint: [...]

2021-01-14 15:08 UTC, julianbrost requested changes
Do you think readers from other time zones will be able to follow this without additional explanation? Maybe rephrase to "on 2020-10-25, where a jump from 2:59 CEST to 2:00 CET happens, 2:30 is interpreted as CEST".

2021-01-14 15:08 UTC, julianbrost commented on doc/09-object-types.md
> +and (the actually not existing) 2021-2-28 2:30 refers to CET (3:30 CEST).
Please add a leading zero to `2021-02-28`.

2021-01-14 16:19 UTC, julianbrost approved these changes

2021-01-14 16:23 UTC, merged