Display logmessage if two nodes run on different versions
Icinga/icinga2 pull request #8088
Opened 2020-07-06 15:34 UTC by Yonas-net

resolves #8075

2020-07-06 15:37 UTC, Al2Klimov commented on lib/remote/apilistener.cpp
> +#include <lib/base/logger.hpp>
Srsly?

2020-07-06 15:39 UTC, Al2Klimov commented on lib/remote/apilistener.cpp
> +				if ((double)params->Get("version") < (double)l_AppVersionInt - 100) {
Make sure `(double)params->Get("version")` is called only once.

2020-07-06 15:49 UTC, Al2Klimov commented on lib/remote/apilistener.cpp
> +				double appVersion = params->Get("version");
Make it of the same datatype as `l_AppVersionInt`.

2020-07-06 16:02 UTC, Al2Klimov commented on lib/remote/apilistener.cpp
> +				endpoint->SetIcingaVersion(appVersion);
Add a newline after this one.

2020-07-06 16:02 UTC, Al2Klimov commented on lib/remote/apilistener.cpp
> +				if (appVersion < (double)l_AppVersionInt - 100) {
What's the cast for?

2020-07-07 10:19 UTC, Al2Klimov commented on lib/remote/apilistener.cpp
> +								<< "Unexpected Icinga version of endpoint '" << endpoint->GetName() << "': " << nodeVersion
This version has three digits...

2020-07-07 10:19 UTC, Al2Klimov commented on lib/remote/apilistener.cpp
> +								<< ". Expected one of: " << l_AppVersionInt << ", " << l_AppVersionInt - 100;
... but these have five.

2020-07-07 13:32 UTC, Al2Klimov commented on lib/remote/apilistener.cpp
> +        << "." << (l_AppVersionInt / 100u - 1u) % 100u << ".x";
Print only `nodeVersion`...

2020-07-07 13:33 UTC, Al2Klimov commented on lib/remote/apilistener.cpp
> +								<< "Unexpected Icinga version of endpoint '" << endpoint->GetName() << "': ");
... and call it here as often as you need it.

2020-07-07 13:34 UTC, Al2Klimov commented on lib/remote/apilistener.cpp
> +							PrintAppVersion(nodeVersion,Log(LogWarning, "ApiListener")
Make `Log(LogWarning, "ApiListener")` a variable `Log log (LogWarning, "ApiListener");` and continue with `log << ...`.

2020-07-07 13:54 UTC, Al2Klimov commented on lib/remote/apilistener.cpp
> +								<< "." << (l_AppVersionInt / 100u - 1u) % 100u << ".x";
Why don't you use the function also here?

2020-07-07 14:07 UTC, Al2Klimov commented on lib/remote/apilistener.cpp
> +							log << " . Expected one of: ";
You don't need a . here.

2020-07-07 14:41 UTC, Yonas-net commented
Testprotocol:
So far it was the problem that if a node runs on 2 versions behind or 1 version before its parent, you could not see any log messages that could indicate this. But this bug has now been fixed and I will illustrate it to you as follows.

Let us assume that the node is version 2.10.x and the master 2.12.x should then see a log message, because it is not allowed to use node that is 2 versions behind master.

Master Version ``v2.12.0`` and node Version ``v2.10.0``.
Output:
```
warning/ApiListener: Unexpected Icinga version of endpoint 'sat': 2.10.x  Expected one of: 2.12.x, 2.11.x
```
However, if the node has the same version as the master or is 1 version behind the master, we do not need a log message because it is allowed.

The master can be 1 version before the node, but the node cannot be 1 version before the master.
```
[2020-07-07 16:40:39 +0200] warning/ApiListener: Unexpected Icinga version of endpoint 'sat': 2.13.x . Expected one of: 2.12.x, 2.11.x
```

2020-07-09 15:12 UTC, Al2Klimov commented
> lto1: internal compiler error: in prune_unused_types_prune, at dwarf2out.c:22275

2020-07-09 15:25 UTC, Al2Klimov commented
If you ask me, that error is pretty silly.

@lazyfrosch Any chance they fix it for CentOS 7?

2020-07-09 15:27 UTC, lazyfrosch commented
Uhm sorry not my expertise

2020-07-09 15:39 UTC, lazyfrosch commented
GCC bugs can occur, especially with older maintained versions. We should find a workaround to avoid the problem.

2020-07-10 11:56 UTC, Al2Klimov commented
This is likely #7149.

2020-07-10 13:26 UTC, Al2Klimov commented
## Blocked by

* [ ] #7905

2020-12-14 14:42 UTC, Al2Klimov requested changes
Rebase with -i. Keep only your commit.

2020-12-16 14:42 UTC, Al2Klimov requested changes

2020-12-16 14:42 UTC, Al2Klimov commented on lib/remote/apilistener.cpp
> +				}
Why did you remove SetCapabilities()?

2020-12-16 15:03 UTC, Yonas-net commented on lib/remote/apilistener.cpp
> +				}
It was not part of my commit.

2020-12-16 15:05 UTC, Al2Klimov commented on lib/remote/apilistener.cpp
> +				}
Come on. Only your commits are here.

2020-12-16 15:14 UTC, Al2Klimov requested changes
Re-test https://github.com/Icinga/icinga2/pull/8088#issuecomment-654911523 (just to be sure).

2021-01-11 07:52 UTC, Yonas-net commented
Tested it and it works fine!

```powershell
[2021-01-11 08:51:25 +0100] information/ApiListener: Finished sending config file updates for endpoint 'satellite' in zone 'satellite'.
[2021-01-11 08:51:25 +0100] warning/ApiListener: Unexpected Icinga version of endpoint 'satellite': 2.10.x Expected one of: 2.12.x, 2.11.x
```

2021-01-11 11:30 UTC, Al2Klimov approved these changes

2021-01-11 11:30 UTC, merged