JsonEncode(): suffix pretty JSON w/ \n
Icinga/icinga2 pull request #8195
Opened 2020-08-27 10:17 UTC by Al2Klimov

fixes #8194

2020-08-27 10:19 UTC, Al2Klimov commented
## Before

```
bash-3.2$ curl -fksSLu root:icinga -H 'Accept: application/json' -X GET 'https://localhost:5665/v1/?pretty=1'
{
    "results": [
        {
            "info": "More information about API requests is available in the documentation at https://icinga.com/docs/icinga2/latest/",
            "permissions": [
                "*"
            ],
            "user": "root",
            "version": "v2.12.0"
        }
    ]
}bash-3.2$
```

## After

```
bash-3.2$ curl -fksSLu root:icinga -H 'Accept: application/json' -X GET 'https://localhost:5665/v1/?pretty=1'
{
    "results": [
        {
            "info": "More information about API requests is available in the documentation at https://icinga.com/docs/icinga2/latest/",
            "permissions": [
                "*"
            ],
            "user": "root",
            "version": "v2.12.0-1-ge5df408c3"
        }
    ]
}
bash-3.2$
```

2020-09-02 08:28 UTC, N-o-X approved these changes

2020-09-02 09:14 UTC, mcktr requested changes
Tests on Windows are failing and on some Linux distributions on the same test:

```
The following tests FAILED:
	 26 - base-base_json/encode (Failed)
powershell.exe : Errors while running CTest
At line:1 char:1
```

2020-09-04 11:19 UTC, mcktr approved these changes

2020-11-13 16:08 UTC, merged