Don't send reminder notifications before suppressed ones
Icinga/icinga2 pull request #8242
Opened 2020-09-17 10:35 UTC by Al2Klimov

fixes #8201

2020-09-17 11:58 UTC, Al2Klimov commented
In this case we still send notifications, but the suppressed ones and only because of disabled active checks. If they were enabled and the switch would recover soon, the suppressed problem notification would disappear as it would no longer apply and no reminders would be sent.

## Before

```
[2020-09-17 12:22:37 +0200] information/Notification: Completed sending 'Recovery' notification 'firewall!icingaadmin' for checkable 'firewall' and user 'icingaadmin' using command 'mail-host-notification'.
[2020-09-17 12:22:37 +0200] notice/Process: PID 70103 ('/Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/scripts/mail-host-notification.sh' '-4' '' '-6' '' '-b' '' '-c' '' '-d' '2020-09-17 12:22:37 +0200' '-l' 'firewall' '-n' 'firewall' '-o' ' ' '-r' 'icinga@localhost' '-s' 'UP' '-t' 'RECOVERY') terminated with exit code 0
[2020-09-17 12:22:39 +0200] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 2; Checks/s: 0
[2020-09-17 12:22:39 +0200] notice/Dependency: Dependency 'switch!firewall' passed: Parent host 'firewall' matches state filter.
[2020-09-17 12:22:39 +0200] notice/NotificationComponent: Attempting to send reminder notification 'switch!icingaadmin'.
[2020-09-17 12:22:39 +0200] notice/Notification: Attempting to send reminder notifications of type 'Problem' for notification object 'switch!icingaadmin'.
[2020-09-17 12:22:39 +0200] debug/Notification: Type 'Problem', TypeFilter: Acknowledgement, Custom, DowntimeEnd, DowntimeRemoved, DowntimeStart, FlappingEnd, FlappingStart, Problem and Recovery (FType=32, TypeFilter=-1)
[2020-09-17 12:22:39 +0200] debug/Notification: State 'Down', StateFilter: Critical, Down, OK, Unknown, Up and Warning (FState=32, StateFilter=-1)
[2020-09-17 12:22:39 +0200] debug/Notification: User 'icingaadmin' notification 'switch!icingaadmin', Type 'Problem', TypeFilter: Acknowledgement, Custom, DowntimeEnd, DowntimeRemoved, DowntimeStart, FlappingEnd, FlappingStart, Problem and Recovery (FType=32, TypeFilter=-1)
[2020-09-17 12:22:39 +0200] debug/Notification: User 'icingaadmin' notification 'switch!icingaadmin', State 'Down', StateFilter: Critical, Down, OK, Unknown, Up and Warning (FState=32, StateFilter=-1)
[2020-09-17 12:22:39 +0200] information/Notification: Sending reminder 'Problem' notification 'switch!icingaadmin' for user 'icingaadmin'
```

## After

```
[2020-09-17 12:31:25 +0200] information/Notification: Completed sending 'Recovery' notification 'firewall!icingaadmin' for checkable 'firewall' and user 'icingaadmin' using command 'mail-host-notification'.
[2020-09-17 12:31:25 +0200] notice/Process: PID 71470 ('/Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/scripts/mail-host-notification.sh' '-4' '' '-6' '' '-b' '' '-c' '' '-d' '2020-09-17 12:31:25 +0200' '-l' 'firewall' '-n' 'firewall' '-o' ' ' '-r' 'icinga@localhost' '-s' 'UP' '-t' 'RECOVERY') terminated with exit code 0
[2020-09-17 12:31:25 +0200] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 2; Checks/s: 0
[2020-09-17 12:31:25 +0200] notice/Dependency: Dependency 'switch!firewall' passed: Parent host 'firewall' matches state filter.
[2020-09-17 12:31:27 +0200] notice/Dependency: Dependency 'switch!firewall' passed: Parent host 'firewall' matches state filter.
[2020-09-17 12:31:27 +0200] notice/ApiListener: Relaying 'event::SendNotifications' message
[2020-09-17 12:31:27 +0200] information/Checkable: Checkable 'switch' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2020-09-17 12:31:27 +0200] notice/ApiListener: Relaying 'event::SetForceNextNotification' message
[2020-09-17 12:31:27 +0200] notice/Notification: Attempting to send notifications of type 'Problem' for notification object 'switch!icingaadmin'.
[2020-09-17 12:31:27 +0200] debug/Notification: Type 'Problem', TypeFilter: Acknowledgement, Custom, DowntimeEnd, DowntimeRemoved, DowntimeStart, FlappingEnd, FlappingStart, Problem and Recovery (FType=32, TypeFilter=-1)
[2020-09-17 12:31:27 +0200] debug/Notification: State 'Down', StateFilter: Critical, Down, OK, Unknown, Up and Warning (FState=32, StateFilter=-1)
[2020-09-17 12:31:27 +0200] debug/Notification: User 'icingaadmin' notification 'switch!icingaadmin', Type 'Problem', TypeFilter: Acknowledgement, Custom, DowntimeEnd, DowntimeRemoved, DowntimeStart, FlappingEnd, FlappingStart, Problem and Recovery (FType=32, TypeFilter=-1)
[2020-09-17 12:31:27 +0200] debug/Notification: User 'icingaadmin' notification 'switch!icingaadmin', State 'Down', StateFilter: Critical, Down, OK, Unknown, Up and Warning (FState=32, StateFilter=-1)
[2020-09-17 12:31:27 +0200] information/Notification: Sending 'Problem' notification 'switch!icingaadmin' for user 'icingaadmin'
```

2020-09-30 08:00 UTC, lippserd commented
@Al2Klimov @N-o-X Are there any expected side effects here? I would suggest to include this fix in 2.11.6 and 2.12.1.

2020-09-30 08:26 UTC, N-o-X commented
@lippserd nope, this should not have any side effects. I think we can safely add this to both versions.

2020-09-30 08:27 UTC, N-o-X requested changes

2020-09-30 08:27 UTC, N-o-X commented on lib/notification/notificationcomponent.cpp
> +			}
Please use the same code style as the rest of the function.

2020-09-30 08:50 UTC, lippserd approved these changes

2020-10-14 09:03 UTC, merged