Optionally drop passive check results for unreachable hosts/services
Icinga/icinga2 pull request #8267
Opened 2020-09-21 16:50 UTC by efuss

I make heavy use of passive check results fed into Icinga by long-running deamons: an snmptrapd plugin deals with SNMP traps possibly announcing table changes (with zero forks), a collectd plugin continuously checks metrics against thresholds including building averages and utilizing hysteresis (again with zero forks).

I also make heavy use of dependencies; in fact, I would argue a monitoring setup without carefully crafted dependencies reducing notifications to those of the root cause seriously degrades it's usefulness.

Now, while dependencies can be made to stop active checks being scheduled upon un-reachability, passive check results are still both issued and processed; the long-running deamons have no notion of reachability (until I teach collectd to gather it by querying IDO or such – but that's another issue).

This inevitably makes the child service go into HARD state during un-reachability because the daemon keeps issuing non-OK results. Then, when the problem resolves, timing may be such that the parent recovers first (host going up) while the child is still dysfunctional (SNMP agent not yet fully up). Meanwhile, the daemon will continue to deliver non-OK states to Icinga, causing superflous notifications.

The remedy is, of course, to (optionally) silently discard passive check results while active checks are not being scheduled. I'm unsure whether it would harm anybody's setup if they were dropped unconditionally.

I introduced a `passive_check_reachability attribute` (I'm not happy with the name, but `ignore_passive_check_results_if_unreachable` isn't nice either) and it solves my problem.
I din't test the API case.

2020-09-22 14:58 UTC, Al2Klimov commented
> Now, while dependencies can be made to stop active checks being scheduled upon un-reachability, passive check results are still both issued and processed;

Why an attribute? Why not to ignore the passive checks the same way as not executing active ones?

https://github.com/Icinga/icinga2/blob/2648a82de0e1ffc1f1441cc448ac655f219fb4bf/lib/checker/checkercomponent.cpp#L132-L136

2020-09-22 15:03 UTC, efuss commented
> Why an attribute? Why not to ignore the passive checks the same way as not executing active ones?

As I wrote in the comment to the Pull Request:

> I'm unsure whether it would harm anybody's setup if they were dropped unconditionally.

Of course, I'm happy with dropping them unconditionally. I just don't want to break other people's setups without discussiong this first.

2020-09-22 15:10 UTC, Al2Klimov commented
`Dependency#disable_checks` [defaults to false](https://icinga.com/docs/icinga2/latest/doc/09-object-types/#dependency), so users have to set it explicitly. If they set it explicitly, they shall expect actually disabled checks.

2020-09-22 15:10 UTC, Al2Klimov requested changes
> I'm happy with dropping them unconditionally.

Please do so.

2020-09-24 17:01 UTC, efuss commented
> Please do so.
OK, there you go.

2020-09-25 07:57 UTC, Al2Klimov commented
Please have a closer look at [the condition used for active checks](https://github.com/Icinga/icinga2/pull/8267#issuecomment-696777878) and yours.

2020-09-25 15:03 UTC, efuss commented
Oops, sorry.

2020-09-25 15:07 UTC, Al2Klimov requested changes
Please squash your commits into the first one.

2020-09-25 15:10 UTC, efuss commented
> Please squash your commits into the first one.
That would require an interactive rebase (e.g., re-writing history) after a push. Is that considered OK?

2020-09-25 15:10 UTC, Al2Klimov commented
Yes.

2020-09-25 15:29 UTC, efuss commented
OK then.

2020-10-29 16:14 UTC, Al2Klimov approved these changes
Why not.

2020-11-24 16:33 UTC, julianbrost requested changes
Code looks good to me but please update the documentation to state that `disable_checks` disables both the execution of active checks and processing of passive check results now.

2021-01-18 14:36 UTC, efuss commented
> please update the documentation
Done.

2021-01-18 17:31 UTC, julianbrost approved these changes

2021-01-19 09:42 UTC, Al2Klimov requested changes
Please squash your commits.

2021-01-19 19:11 UTC, efuss commented
> Please squash your commits.
Oh well. I can't remember which projects prefer this and for which it's a no-go.

2021-01-20 16:07 UTC, Al2Klimov approved these changes

2021-01-20 16:07 UTC, merged