Add itl http and dns changes
Icinga/icinga2 pull request #8297
Opened 2020-09-29 13:42 UTC by mzac

Add two options to the ITL DNS and HTTP checks

2020-09-30 10:12 UTC, Al2Klimov commented on itl/command-plugins.conf
> +		}
-q? AFAIK there's no -q:

https://github.com/monitoring-plugins/monitoring-plugins/blob/739a7bbe7ceacab9809998d9bf06a4460b44c522/plugins/check_dns.c#L547-L563

2020-09-30 10:12 UTC, Al2Klimov commented on itl/command-plugins.conf
> +		}
Same here:

https://github.com/monitoring-plugins/monitoring-plugins/blob/739a7bbe7ceacab9809998d9bf06a4460b44c522/plugins/check_http.c

2020-09-30 17:55 UTC, mzac commented
@Al2Klimov I am running on a Redhat system.  We seem to have an internal repo but it seems to be mirroring the plugins from www.nagios-plugins.org  

```
Installed Packages
Name        : nagios-plugins-http
Arch        : x86_64
Version     : 2.3.3
Release     : 2.el7
Size        : 106 k
Repo        : installed
From repo   : McGill_University_EPEL_7Server_EPEL_7Server_x86_64
Summary     : Nagios Plugin - check_http
URL         : https://www.nagios-plugins.org/
License     : GPLv2+
Description : Provides check_http support for Nagios.
```

These packages do have these options:
https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_http.c#L238
https://github.com/nagios-plugins/nagios-plugins/blob/master/plugins/check_dns.c#L211

2020-10-01 07:48 UTC, Al2Klimov requested changes
1. Drop the http_verify_host commits in favor of #8005.
2. Add [a note](https://github.com/Icinga/icinga2/pull/8005/files#diff-e3021f9a13beebb1e13d11aba1923e31R667) telling dns_query_type is supported only by Nagios plugins.
3. Squash the dns_query_type commits.
3.

2020-10-01 07:48 UTC, Al2Klimov commented on doc/10-icinga-template-library.md
> +dns_query_type       | **Optional.** The DNS record query type where TYPE =(A, AAAA, SRV, TXT, MX, ANY). The default query type is 'A' (IPv4 host entry)
IMO "where TYPE =" is redundant.

2020-10-01 07:48 UTC, Al2Klimov commented on itl/command-plugins.conf
> +			description = "Optional DNS record query type where TYPE =(A, AAAA, SRV, TXT, MX, ANY). The default query type is 'A' (IPv4 host entry)"
Same here.

2020-10-01 07:48 UTC, Al2Klimov commented on itl/command-plugins.conf
> +	vars.dns_query_type = "A"
Is a default value actually required?

2021-09-09 10:29 UTC, julianbrost commented
@mzac I'm closing this for now as it hasn't seen any activity for some time now and we don't consider this change important enough to put in the time to fix the remaining issues ourselves. If you still want to work on this, feel free to reopen it at any time.

2021-09-09 10:29 UTC, closed without merging