Feature/Add support Influxdb basic auth
Icinga/icinga2 pull request #8314
Opened 2020-10-07 14:27 UTC by Yonas-net

fixes #7644

2020-10-07 14:31 UTC, Al2Klimov requested changes

2020-10-07 14:31 UTC, Al2Klimov commented on lib/perfdata/influxdbwriter.cpp
> +	Dictionary::Ptr basic_auth = GetBasicAuth();
Please create new variables with camelCase.

2020-10-07 14:31 UTC, Al2Klimov commented on lib/perfdata/influxdbwriter.cpp
> +		Log(LogInformation, "Icinga2 uses basic authentication to connect to InfluxDB server");
What's this for?

2020-10-07 14:31 UTC, Al2Klimov commented on lib/perfdata/influxdbwriter.cpp
> +		BOOST_THROW_EXCEPTION(ValidationError(this, { "basic_auth", "password" }, "Basic authentication password must to be not empty."));
Do you actually need this?

2020-10-07 14:54 UTC, Al2Klimov requested changes

2020-10-07 14:54 UTC, Al2Klimov commented on lib/perfdata/influxdbwriter.cpp
> +	}
I'd make this a `{` `}` block.

2020-10-07 14:54 UTC, Al2Klimov commented on lib/perfdata/influxdbwriter.cpp
> +}
What's this for?

2020-10-07 15:03 UTC, Al2Klimov requested changes

2020-10-07 15:03 UTC, Al2Klimov commented on lib/perfdata/influxdbwriter.cpp
> -
Not part of the task.

2020-10-07 15:09 UTC, Al2Klimov requested changes
Write a test protocol.

2020-10-07 15:21 UTC, Yonas-net commented
Testprotocol: Basic_Auth

With the configs shown above icinga2 output looks like this.

```
icinga2_1           | [2020-10-07 15:14:33 +0000] warning/InfluxdbWriter: Unexpected response code: Unauthorized
nginx-service_1     | 172.18.0.2 - - [07/Oct/2020:15:14:33 +0000] "POST /write?db=icinga2&precision=s HTTP/1.0" 401 179 "-" "Icinga/v2.12.0-3-gdf8e0cd8a" "-"
icinga2_1           | [2020-10-07 15:14:33 +0000] warning/InfluxdbWriter: Unexpected Content-Type: text/html
icinga2_1           | [2020-10-07 15:14:43 +0000] warning/InfluxdbWriter: Unexpected response code: Unauthorized
icinga2_1           | [2020-10-07 15:14:43 +0000] warning/InfluxdbWriter: Unexpected Content-Type: text/html
nginx-service_1     | 172.18.0.2 - - [07/Oct/2020:15:14:43 +0000] "POST /write?db=icinga2&precision=s HTTP/1.0" 401 179 "-" "Icinga/v2.12.0-3-gdf8e0cd8a" "-"
```

And then after I add the correct authentication config to the ``Icinga2 influxdb.conf`` file.
```
basic_auth = {
     username = "icinga"
     password = "icinga"
}
```

Icinga2 is able to connect to InluxDB server using the basic auth method.
```
icinga2_1           | [2020-10-07 15:20:04 +0000] information/WorkQueue: #5 (InfluxdbWriter, influxdb) items: 0, rate: 0.0166667/s (1/min 1/5min 1/15min);
influxdb-service_1  | [httpd] 172.20.0.4 - icinga [07/Oct/2020:15:20:14 +0000] "POST /write?db=icinga2&precision=s HTTP/1.0" 204 0 "-" "Icinga/v2.12.0-3-gdf8e0cd8a" 9979f4dc-08b0-11eb-8001-0242ac140003 17204
nginx-service_1     | 172.20.0.2 - icinga [07/Oct/2020:15:20:14 +0000] "POST /write?db=icinga2&precision=s HTTP/1.0" 204 0 "-" "Icinga/v2.12.0-3-gdf8e0cd8a" "-"
influxdb-service_1  | [httpd] 172.20.0.4 - icinga [07/Oct/2020:15:20:24 +0000] "POST /write?db=icinga2&precision=s HTTP/1.0" 204 0 "-" "Icinga/v2.12.0-3-gdf8e0cd8a" 9f6d9696-08b0-11eb-8002-0242ac140003 2342
nginx-service_1     | 172.20.0.2 - icinga [07/Oct/2020:15:20:24 +0000] "POST /write?db=icinga2&precision=s HTTP/1.0" 204 0 "-" "Icinga/v2.12.0-3-gdf8e0cd8a" "-"
influxdb-service_1  | [httpd] 172.20.0.4 - icinga [07/Oct/2020:15:20:34 +0000] "POST /write?db=icinga2&precision=s HTTP/1.0" 204 0 "-" "Icinga/v2.12.0-3-gdf8e0cd8a" a5647d2d-08b0-11eb-8003-0242ac140003 2912
nginx-service_1     | 172.20.0.2 - icinga [07/Oct/2020:15:20:34 +0000] "POST /write?db=icinga2&precision=s HTTP/1.0" 204 0 "-" "Icinga/v2.12.0-3-gdf8e0cd8a" "-"
```

2020-10-07 15:22 UTC, Al2Klimov requested changes
Adjust the docs.

2020-10-07 15:57 UTC, Al2Klimov requested changes
Squash everything.

2020-10-07 16:00 UTC, Al2Klimov approved these changes

2020-10-08 11:45 UTC, Al2Klimov commented
What happens if you use this branch, but not specify basic auth?

2020-10-08 12:03 UTC, Yonas-net commented
> What happens if you use this branch, but not specify basic auth?

I removed basic_auth completely from the config and this happens:
```
nginx-service_1     | 172.20.0.2 - - [08/Oct/2020:11:58:02 +0000] "POST /write?db=icinga2&precision=s HTTP/1.0" 401 179 "-" "Icinga/v2.12.0-3-gdf8e0cd8a" "-"
nginx-service_1     | 172.20.0.2 - - [08/Oct/2020:11:58:12 +0000] "POST /write?db=icinga2&precision=s HTTP/1.0" 401 179 "-" "Icinga/v2.12.0-3-gdf8e0cd8a" "-"
icinga2_1           | [2020-10-08 11:58:12 +0000] warning/InfluxdbWriter: Unexpected response code: Unauthorized
icinga2_1           | [2020-10-08 11:58:12 +0000] warning/InfluxdbWriter: Unexpected Content-Type: text/html
```

2020-12-02 15:03 UTC, julianbrost requested changes
With this, the new basic auth credentials can be queried using the API. This is not the case for the existing password field.

```
$ curl -ksSu root:icinga -H 'Accept: application/json' -X GET https://localhost:5665/v1/objects/influxdbwriters/influxdb | jq
[...]
        "basic_auth": {
          "password": "bar",
          "username": "foo"
        },
[...]
```

2020-12-03 08:19 UTC, julianbrost approved these changes
Looks good to me now.

I was also thinking about adding an attribute like `auth_method` instead which can either take `url` or `basic` as a value. This should suffice for what is described in the corresponding issue, however, I guess you can also build setups with a reverse-proxy where you might want to use both authentication mechanisms with different credentials. So fine for me as it is right now.

2020-12-03 09:59 UTC, Al2Klimov approved these changes

2020-12-03 10:00 UTC, merged