Forbid dependency cycles
Icinga/icinga2 pull request #8389
Opened 2020-10-20 10:32 UTC by Al2Klimov

2020-10-20 10:33 UTC, Al2Klimov commented
```
➜  icinga2 git:(d0ac25cbc) cat just-dc1.conf
object CheckCommand "dummy" {
	import "dummy-check-command"

	vars.dummy_state = 0
	vars.dummy_text = "Check was successful."
}

object CheckCommand "passive" {
	import "dummy"

	vars.dummy_state = 3
	vars.dummy_text = "No Passive Check Result Received."
}

object Host "h1" {
	check_command = "passive"
}

object Dependency "h1" {
	parent_host_name = "h1"
	child_host_name = "h1"
}
➜  icinga2 git:(d0ac25cbc) cat just-dc2.conf
object CheckCommand "dummy" {
	import "dummy-check-command"

	vars.dummy_state = 0
	vars.dummy_text = "Check was successful."
}

object CheckCommand "passive" {
	import "dummy"

	vars.dummy_state = 3
	vars.dummy_text = "No Passive Check Result Received."
}

object Host "h1" {
	check_command = "passive"
}

object Host "h2" {
	check_command = "passive"
}

object Dependency "h1" {
	parent_host_name = "h1"
	child_host_name = "h2"
}

object Dependency "h2" {
	parent_host_name = "h2"
	child_host_name = "h1"
}
➜  icinga2 git:(d0ac25cbc) cat just-dc3.conf
object CheckCommand "dummy" {
	import "dummy-check-command"

	vars.dummy_state = 0
	vars.dummy_text = "Check was successful."
}

object CheckCommand "passive" {
	import "dummy"

	vars.dummy_state = 3
	vars.dummy_text = "No Passive Check Result Received."
}

object Host "h1" {
	check_command = "passive"
}

object Service "s1" {
	host_name = "h1"
	check_command = "passive"
}

object Dependency "s1" {
	parent_host_name = "h1"
	parent_service_name = "s1"
	child_host_name = "h1"
}
➜  icinga2 git:(d0ac25cbc) cat just-dc4.conf
object CheckCommand "dummy" {
	import "dummy-check-command"

	vars.dummy_state = 0
	vars.dummy_text = "Check was successful."
}

object CheckCommand "passive" {
	import "dummy"

	vars.dummy_state = 3
	vars.dummy_text = "No Passive Check Result Received."
}

object Host "h1" {
	check_command = "passive"
}

object Host "h2" {
	check_command = "passive"
}

object Dependency "h1" {
	parent_host_name = "h1"
	child_host_name = "h2"
}
➜  icinga2 git:(d0ac25cbc) prefix/sbin/icinga2 daemon -C -c just-dc1.conf
[2020-10-20 12:29:03 +0200] information/cli: Icinga application loader (version: v2.12.0-2-gd0ac25cbc)
[2020-10-20 12:29:03 +0200] information/cli: Loading configuration file(s).
[2020-10-20 12:29:03 +0200] information/ConfigItem: Committing config item(s).
[2020-10-20 12:29:03 +0200] information/ConfigItem: Instantiated 2 CheckCommands.
[2020-10-20 12:29:03 +0200] information/ConfigItem: Instantiated 1 Dependency.
[2020-10-20 12:29:03 +0200] information/ConfigItem: Instantiated 1 Host.
[2020-10-20 12:29:03 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-10-20 12:29:03 +0200] critical/config: Error: Dependency cycle: Host 'h1' -> Dependency 'h1!h1' -> Host 'h1'

[2020-10-20 12:29:03 +0200] critical/cli: Config validation failed. Re-run with 'icinga2 daemon -C' after fixing the config.
➜  icinga2 git:(d0ac25cbc) prefix/sbin/icinga2 daemon -C -c just-dc2.conf
[2020-10-20 12:29:12 +0200] information/cli: Icinga application loader (version: v2.12.0-2-gd0ac25cbc)
[2020-10-20 12:29:12 +0200] information/cli: Loading configuration file(s).
[2020-10-20 12:29:12 +0200] information/ConfigItem: Committing config item(s).
[2020-10-20 12:29:12 +0200] information/ConfigItem: Instantiated 2 CheckCommands.
[2020-10-20 12:29:12 +0200] information/ConfigItem: Instantiated 2 Dependencies.
[2020-10-20 12:29:12 +0200] information/ConfigItem: Instantiated 2 Hosts.
[2020-10-20 12:29:12 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-10-20 12:29:12 +0200] critical/config: Error: Dependency cycle: Host 'h2' -> Dependency 'h2!h1' -> Host 'h1' -> Dependency 'h1!h2' -> Host 'h2'

[2020-10-20 12:29:12 +0200] critical/cli: Config validation failed. Re-run with 'icinga2 daemon -C' after fixing the config.
➜  icinga2 git:(d0ac25cbc) prefix/sbin/icinga2 daemon -C -c just-dc3.conf
[2020-10-20 12:29:28 +0200] information/cli: Icinga application loader (version: v2.12.0-2-gd0ac25cbc)
[2020-10-20 12:29:28 +0200] information/cli: Loading configuration file(s).
[2020-10-20 12:29:28 +0200] information/ConfigItem: Committing config item(s).
[2020-10-20 12:29:28 +0200] information/ConfigItem: Instantiated 2 CheckCommands.
[2020-10-20 12:29:28 +0200] information/ConfigItem: Instantiated 1 Dependency.
[2020-10-20 12:29:28 +0200] information/ConfigItem: Instantiated 1 Host.
[2020-10-20 12:29:28 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-10-20 12:29:28 +0200] information/ConfigItem: Instantiated 1 Service.
[2020-10-20 12:29:28 +0200] critical/config: Error: Dependency cycle: Host 'h1' -> Dependency 'h1!s1' -> Service 'h1!s1' -> Host 'h1'

[2020-10-20 12:29:28 +0200] critical/cli: Config validation failed. Re-run with 'icinga2 daemon -C' after fixing the config.
➜  icinga2 git:(d0ac25cbc) prefix/sbin/icinga2 daemon -C -c just-dc4.conf
[2020-10-20 12:30:41 +0200] information/cli: Icinga application loader (version: v2.12.0-2-gd0ac25cbc)
[2020-10-20 12:30:41 +0200] information/cli: Loading configuration file(s).
[2020-10-20 12:30:41 +0200] information/ConfigItem: Committing config item(s).
[2020-10-20 12:30:41 +0200] information/ConfigItem: Instantiated 2 CheckCommands.
[2020-10-20 12:30:41 +0200] information/ConfigItem: Instantiated 1 Dependency.
[2020-10-20 12:30:41 +0200] information/ConfigItem: Instantiated 2 Hosts.
[2020-10-20 12:30:41 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-10-20 12:30:41 +0200] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2020-10-20 12:30:41 +0200] information/cli: Finished validating the configuration file(s).
➜  icinga2 git:(d0ac25cbc)
```

2020-11-10 09:36 UTC, lippserd commented
I'd like to postpone this PR. I can imagine that the performance will suffer for configurations with many dependencies with this PR . @N-o-X @Al2Klimov Any objections?

2020-11-10 11:53 UTC, Al2Klimov commented
You seem to be wrong.

## v2.12.0

```
➜  icinga2 git:(338d0aaa8) prefix/sbin/icinga2 daemon -C -c 8389.conf
[2020-11-10 12:14:09 +0100] information/cli: Icinga application loader (version: v2.12.0)
[2020-11-10 12:14:09 +0100] information/cli: Loading configuration file(s).
[2020-11-10 12:14:10 +0100] information/ConfigItem: Committing config item(s).
[2020-11-10 12:14:20 +0100] information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 0, rate: 11.3333/s (680/min 680/5min 680/15min);
[2020-11-10 12:17:55 +0100] information/ConfigItem: Instantiated 1 CheckCommand.
[2020-11-10 12:17:55 +0100] information/ConfigItem: Instantiated 900000 Dependencies.
[2020-11-10 12:17:55 +0100] information/ConfigItem: Instantiated 100000 Hosts.
[2020-11-10 12:17:55 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-10 12:17:55 +0100] information/ConfigItem: Instantiated 1000000 Services.
[2020-11-10 12:17:55 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2020-11-10 12:17:55 +0100] information/cli: Finished validating the configuration file(s).
➜  icinga2 git:(338d0aaa8) prefix/sbin/icinga2 daemon -C -c 8389.conf
[2020-11-10 12:18:25 +0100] information/cli: Icinga application loader (version: v2.12.0)
[2020-11-10 12:18:25 +0100] information/cli: Loading configuration file(s).
[2020-11-10 12:18:25 +0100] information/ConfigItem: Committing config item(s).
[2020-11-10 12:18:35 +0100] information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 0, rate: 16/s (960/min 960/5min 960/15min);
[2020-11-10 12:21:52 +0100] information/ConfigItem: Instantiated 1 CheckCommand.
[2020-11-10 12:21:52 +0100] information/ConfigItem: Instantiated 900000 Dependencies.
[2020-11-10 12:21:52 +0100] information/ConfigItem: Instantiated 100000 Hosts.
[2020-11-10 12:21:52 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-10 12:21:52 +0100] information/ConfigItem: Instantiated 1000000 Services.
[2020-11-10 12:21:52 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2020-11-10 12:21:52 +0100] information/cli: Finished validating the configuration file(s).
➜  icinga2 git:(338d0aaa8) prefix/sbin/icinga2 daemon -C -c 8389.conf
[2020-11-10 12:23:00 +0100] information/cli: Icinga application loader (version: v2.12.0)
[2020-11-10 12:23:00 +0100] information/cli: Loading configuration file(s).
[2020-11-10 12:23:01 +0100] information/ConfigItem: Committing config item(s).
[2020-11-10 12:23:11 +0100] information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 0, rate: 16/s (960/min 960/5min 960/15min);
[2020-11-10 12:26:19 +0100] information/ConfigItem: Instantiated 1000000 Services.
[2020-11-10 12:26:19 +0100] information/ConfigItem: Instantiated 1 CheckCommand.
[2020-11-10 12:26:19 +0100] information/ConfigItem: Instantiated 900000 Dependencies.
[2020-11-10 12:26:19 +0100] information/ConfigItem: Instantiated 100000 Hosts.
[2020-11-10 12:26:19 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-10 12:26:19 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2020-11-10 12:26:19 +0100] information/cli: Finished validating the configuration file(s).
➜  icinga2 git:(338d0aaa8)
```

## #8389

```
➜  icinga2 git:(feature/forbid-dep-cycles) prefix/sbin/icinga2 daemon -C -c 8389.conf
[2020-11-10 12:39:29 +0100] information/cli: Icinga application loader (version: v2.12.0-2-gd0ac25cbc)
[2020-11-10 12:39:29 +0100] information/cli: Loading configuration file(s).
[2020-11-10 12:39:30 +0100] information/ConfigItem: Committing config item(s).
[2020-11-10 12:39:40 +0100] information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 0, rate: 16/s (960/min 960/5min 960/15min);
[2020-11-10 12:41:30 +0100] information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 1, rate: 10/s (600/min 1920/5min 1920/15min);
[2020-11-10 12:42:48 +0100] information/ConfigItem: Instantiated 1 CheckCommand.
[2020-11-10 12:42:48 +0100] information/ConfigItem: Instantiated 900000 Dependencies.
[2020-11-10 12:42:48 +0100] information/ConfigItem: Instantiated 100000 Hosts.
[2020-11-10 12:42:48 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-10 12:42:48 +0100] information/ConfigItem: Instantiated 1000000 Services.
[2020-11-10 12:42:52 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2020-11-10 12:42:52 +0100] information/cli: Finished validating the configuration file(s).
➜  icinga2 git:(feature/forbid-dep-cycles) prefix/sbin/icinga2 daemon -C -c 8389.conf
[2020-11-10 12:43:22 +0100] information/cli: Icinga application loader (version: v2.12.0-2-gd0ac25cbc)
[2020-11-10 12:43:22 +0100] information/cli: Loading configuration file(s).
[2020-11-10 12:43:23 +0100] information/ConfigItem: Committing config item(s).
[2020-11-10 12:43:33 +0100] information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 0, rate: 16/s (960/min 960/5min 960/15min);
[2020-11-10 12:46:59 +0100] information/ConfigItem: Instantiated 1 CheckCommand.
[2020-11-10 12:46:59 +0100] information/ConfigItem: Instantiated 900000 Dependencies.
[2020-11-10 12:46:59 +0100] information/ConfigItem: Instantiated 100000 Hosts.
[2020-11-10 12:46:59 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-10 12:46:59 +0100] information/ConfigItem: Instantiated 1000000 Services.
[2020-11-10 12:47:03 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2020-11-10 12:47:03 +0100] information/cli: Finished validating the configuration file(s).
➜  icinga2 git:(feature/forbid-dep-cycles) prefix/sbin/icinga2 daemon -C -c 8389.conf
[2020-11-10 12:47:19 +0100] information/cli: Icinga application loader (version: v2.12.0-2-gd0ac25cbc)
[2020-11-10 12:47:19 +0100] information/cli: Loading configuration file(s).
[2020-11-10 12:47:19 +0100] information/ConfigItem: Committing config item(s).
[2020-11-10 12:47:29 +0100] information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 0, rate: 16/s (960/min 960/5min 960/15min);
[2020-11-10 12:50:37 +0100] information/ConfigItem: Instantiated 1 CheckCommand.
[2020-11-10 12:50:37 +0100] information/ConfigItem: Instantiated 900000 Dependencies.
[2020-11-10 12:50:37 +0100] information/ConfigItem: Instantiated 100000 Hosts.
[2020-11-10 12:50:37 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-10 12:50:37 +0100] information/ConfigItem: Instantiated 1000000 Services.
[2020-11-10 12:50:41 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2020-11-10 12:50:41 +0100] information/cli: Finished validating the configuration file(s).
➜  icinga2 git:(feature/forbid-dep-cycles)
```

2020-11-10 13:07 UTC, lippserd commented
> You seem to be wrong.

I am glad I am 😆

2020-11-10 13:07 UTC, lippserd approved these changes

2021-08-04 12:21 UTC, Al2Klimov commented
@cla-bot check

2023-01-17 14:52 UTC, julianbrost requested changes
Looks useful in general, but I'd change a few things:

1. Don't use signals, just call the functions directly. I don't see a benefit in using them here, it just adds another indirection.
2. Error message could be changed to a multi-line format. This should make it more readable in case of longer cycles.
3. Also check for newly introduces cycles when adding dependencies via the API.

2023-01-17 14:52 UTC, julianbrost commented on lib/icinga/dependency.cpp
> +		}
Is that supposed to model the implicit service to host dependency? If so, it would be good to clearly indicate this, including in the error message.

2023-02-06 10:02 UTC, julianbrost reviewed
Please include an up-to-date example in the description of how the error messages look like now, including how it looks like when attempting to add a cycle at runtime.

2023-02-06 10:40 UTC, julianbrost commented on lib/icinga/dependency.cpp
> +			graph.Stack.erase(graph.Stack.begin() + (graph.Stack.size() - 1u));
The same is also done just a few lines below.

2023-02-10 16:12 UTC, julianbrost approved these changes

2023-02-10 16:26 UTC, merged