Added new options for ipmi-sensor to ITL
Icinga/icinga2 pull request #8498
Opened 2020-11-23 12:57 UTC by MarcusCaepio

Regarding my PR at https://github.com/thomas-krenn/check_ipmi_sensor_v3/pull/42
I want to add the new options to the Icinga ITL.

2020-11-24 12:09 UTC, Al2Klimov requested changes
Consider putting "--fru is mandatory" at the end and in ( ).

Don't forget to use `git commit --amend`.

2020-11-24 12:09 UTC, Al2Klimov commented on itl/plugins-contrib.d/ipmi.conf
> +			description = "--fru is mandatory. Print the assettag if it is available in the IPMI FRU data."
Why is here a full stop at the end, ...

2020-11-24 12:09 UTC, Al2Klimov commented on itl/plugins-contrib.d/ipmi.conf
> +			description = "--fru is mandatory. Print additional motherboard information if it is available in the IPMI FRU data"
... but here not.

2020-11-24 12:09 UTC, Al2Klimov commented on doc/10-icinga-template-library.md
> +ipmi_show_board                  | **Optional.** --fru is mandatory. Print additional motherboard informations if it is available in the IPMI FRU data.
Same here.

2020-11-25 15:14 UTC, MarcusCaepio commented on doc/10-icinga-template-library.md
> +ipmi_show_board                  | **Optional.** --fru is mandatory. Print additional motherboard informations if it is available in the IPMI FRU data.
Corrected like you wanted.

2020-11-25 15:16 UTC, Al2Klimov approved these changes

2020-12-02 10:37 UTC, julianbrost approved these changes

2020-12-02 11:24 UTC, merged