FireSuppressedNotifications(const Notification::Ptr&): don't send notifications while suppressed by checkable
Icinga/icinga2 pull request #8513
Opened 2020-11-27 17:45 UTC by Al2Klimov

fixes #8509

2020-11-27 17:46 UTC, Al2Klimov commented
## Before

#8509

## After

```
➜  icinga2 git:(bugfix/notifications-downtime-change-in-timeperiod-8509) cat 8509.conf
object CheckerComponent "cc" { }
object NotificationComponent "nc" { }

object CheckCommand "dummy" {
        import "dummy-check-command"
}

object Host "8509" {
        check_command = "dummy"
        #max_check_attempts = 1
        check_interval = 10s

        var that = this
        var commitTime = get_time()

        vars.dummy_state = function() use(that, commitTime) {
                return if (get_time() - commitTime < 1m) { 0 } else { 2 }
        }
        vars.dummy_text = " "
}

object NotificationCommand "false" {
        command = [ "false" ]
}

object User "me" {
}

object TimePeriod "8509" {
        ranges = {
                "friday" = "18:35-18:45"
        }
}

object Notification "8509" {
        host_name = "8509"
        command = "false"
        users = [ "me" ]
        period = "8509"
}

object Downtime "8509" {
        host_name = "8509"
        author = "me"
        comment = "8509"
        start_time = get_time() + 5m
        end_time = start_time + 10m
        fixed = true
}
➜  icinga2 git:(bugfix/notifications-downtime-change-in-timeperiod-8509) prefix/sbin/icinga2 daemon -x notice -c 8509.conf
[2020-11-27 18:26:05 +0100] information/cli: Icinga application loader (version: v2.12.0-186-gc0e843cfa)
[2020-11-27 18:26:05 +0100] notice/cli: Spawning seemless worker process doing the actual work
[2020-11-27 18:26:05 +0100] notice/cli: Spawned worker process (PID 11980), waiting for it to load its config
[2020-11-27 18:26:05 +0100] information/cli: Loading configuration file(s).
[2020-11-27 18:26:05 +0100] notice/ConfigCompiler: Compiling config file: 8509.conf
[2020-11-27 18:26:05 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/include.conf
[2020-11-27 18:26:05 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/8c30df0e-9af9-47dc-ae0a-54bafc02262f/include.conf
[2020-11-27 18:26:05 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/api/packages/_api/8c30df0e-9af9-47dc-ae0a-54bafc02262f/../active.conf
[2020-11-27 18:26:05 +0100] information/ConfigItem: Committing config item(s).
[2020-11-27 18:26:05 +0100] notice/WorkQueue: Spawning WorkQueue threads for 'DaemonUtility::LoadConfigFiles'
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 CheckCommand.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 Downtime.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 Host.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 Notification.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 NotificationCommand.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 TimePeriod.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 User.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-11-27 18:26:05 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2020-11-27 18:26:05 +0100] notice/WorkQueue: Stopped WorkQueue threads for 'DaemonUtility::LoadConfigFiles'
[2020-11-27 18:26:05 +0100] notice/cli: Notifying umbrella process (PID 11966) about the config loading success
[2020-11-27 18:26:05 +0100] notice/cli: Worker process successfully loaded its config
[2020-11-27 18:26:05 +0100] notice/cli: Waiting for the umbrella process to let us doing the actual work
[2020-11-27 18:26:05 +0100] notice/cli: The umbrella process let us continuing
[2020-11-27 18:26:05 +0100] notice/ConfigCompiler: Compiling config file: /Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/modified-attributes.conf
[2020-11-27 18:26:05 +0100] information/ConfigItem: Triggering Start signal for config items
[2020-11-27 18:26:05 +0100] notice/Downtime: Checkable '8509' already in a NOT-OK state. Triggering downtime now.
[2020-11-27 18:26:05 +0100] information/NotificationComponent: 'nc' started.
[2020-11-27 18:26:05 +0100] information/CheckerComponent: 'cc' started.
[2020-11-27 18:26:05 +0100] information/ConfigItem: Activated all objects.
[2020-11-27 18:26:05 +0100] notice/WorkQueue: Stopped WorkQueue threads for 'DaemonCommand::Run'
[2020-11-27 18:26:05 +0100] notice/ApiListener: Updating object authority for local objects.
[2020-11-27 18:26:05 +0100] notice/Checkable: State Change: Checkable '8509' hard state change from DOWN to UP detected.
[2020-11-27 18:26:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:26:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0333333
[2020-11-27 18:26:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0333333
[2020-11-27 18:26:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.05
[2020-11-27 18:26:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.05
[2020-11-27 18:26:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0666667
[2020-11-27 18:26:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0666667
[2020-11-27 18:26:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0833333
[2020-11-27 18:26:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0833333
[2020-11-27 18:26:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:27:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:27:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:27:10 +0100] notice/Checkable: State Change: Checkable '8509' soft state change from UP to DOWN detected.
[2020-11-27 18:27:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.116667
[2020-11-27 18:27:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:27:20 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.1
[2020-11-27 18:27:25 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0833333
[2020-11-27 18:27:30 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0833333
[2020-11-27 18:27:35 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0666667
[2020-11-27 18:27:40 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0666667
[2020-11-27 18:27:45 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.05
[2020-11-27 18:27:50 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.05
[2020-11-27 18:27:55 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0333333
[2020-11-27 18:28:00 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0333333
[2020-11-27 18:28:05 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:28:07 +0100] notice/Checkable: State Change: Checkable '8509' soft state change from DOWN to DOWN detected.
[2020-11-27 18:28:10 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkables: 1; Checks/s: 0.0166667
[2020-11-27 18:28:15 +0100] notice/CheckerComponent: Pending checkables: 0; Idle checkable [...]

2021-01-27 14:15 UTC, julianbrost requested changes
Seems fine, I just find the documentation comment hard to read, see my suggestion.

2021-01-27 14:15 UTC, julianbrost commented on lib/icinga/checkable-notification.cpp
> + */
```suggestion
/**
 * Checks if notifications of a given type should be suppressed for this Checkable at the moment.
 *
 * @param type The notification type for which to query the suppression status.
 *
 * @return true if no notification of this type should be sent.
 */
```

2021-01-27 15:58 UTC, julianbrost approved these changes
LGTM, feel free to squash the commits.

2021-01-27 16:02 UTC, Al2Klimov commented
Too bad Eric forbid that in such cases.

2021-01-28 09:01 UTC, merged