Icinga DB: support TLS
Icinga/icinga2 pull request #8544
Opened 2020-12-09 15:32 UTC by Al2Klimov

2020-12-09 16:00 UTC, Al2Klimov commented
## Test protocol

### Poor man's TLS

```bash
redis-server --tls-port 6380 --tls-cert-file /pki/rd/issued/127.0.0.1.crt --tls-key-file /pki/rd/private/127.0.0.1.key --tls-ca-cert-file /pki/i2/ca.crt --tls-auth-clients no
```

```
➜  icinga2 git:(feature/icingadb-tls) cat prefix/etc/icinga2/features-available/icingadb.conf
object IcingaDB "icingadb" {
  host = "127.0.0.1"
  port = 6397
  use_tls = true
  #cert_path = "icingadb-tls/i2/issued/127.0.0.1.crt"
  #key_path = "icingadb-tls/i2/private/127.0.0.1.key"
  #ca_path = "icingadb-tls/rd/ca.crt"
}
➜  icinga2 git:(feature/icingadb-tls) prefix/sbin/icinga2 daemon
[2020-12-09 16:28:28 +0100] information/cli: Icinga application loader (version: v2.12.0-367-gf10375b8f)
[2020-12-09 16:28:28 +0100] information/cli: Loading configuration file(s).
[2020-12-09 16:28:28 +0100] information/ConfigItem: Committing config item(s).
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 235 CheckCommands.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 1 Endpoint.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 1 Host.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 2 HostGroups.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 12 Notifications.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 2 NotificationCommands.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 3 Zones.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 11 Services.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 3 ServiceGroups.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 3 TimePeriods.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 1 User.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 1 UserGroup.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Instantiated 1 IcingaDB.
[2020-12-09 16:28:28 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2020-12-09 16:28:28 +0100] information/ConfigObject: Restoring program state from file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2020-12-09 16:28:28 +0100] information/ConfigObject: Restored 281 objects. Loaded 0 new objects without state.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Triggering Start signal for config items
[2020-12-09 16:28:28 +0100] information/FileLogger: 'main-log' started.
[2020-12-09 16:28:28 +0100] information/IcingaDB: 'icingadb' started.
[2020-12-09 16:28:28 +0100] information/IcingaDB: Trying to connect to Redis server (async, TLS) on host '127.0.0.1:6397'
[2020-12-09 16:28:28 +0100] information/NotificationComponent: 'notification' started.
[2020-12-09 16:28:28 +0100] information/ConfigItem: Activated all objects.
[2020-12-09 16:28:28 +0100] information/IcingaDB: Connected to Redis server
[2020-12-09 16:28:38 +0100] information/WorkQueue: #5 (IcingaDB) items: 0, rate: 0.0166667/s (1/min 1/5min 1/15min);
[2020-12-09 16:28:43 +0100] information/IcingaDB: Initial config/status dump finished in 0.209579 seconds.
^C[2020-12-09 16:29:06 +0100] information/Application: Received request to shut down.
[2020-12-09 16:29:06 +0100] information/Application: Shutting down...
[2020-12-09 16:29:06 +0100] information/NotificationComponent: 'notification' stopped.
[2020-12-09 16:29:06 +0100] information/IcingaDB: 'icingadb' stopped.
[2020-12-09 16:29:06 +0100] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2020-12-09 16:29:06 +0100] information/IcingaApplication: Icinga has shut down.
➜  icinga2 git:(feature/icingadb-tls)
```

### Server authn

```bash
redis-server --tls-port 6380 --tls-cert-file /pki/rd/issued/127.0.0.1.crt --tls-key-file /pki/rd/private/127.0.0.1.key --tls-ca-cert-file /pki/i2/ca.crt --tls-auth-clients no
```

```
➜  icinga2 git:(feature/icingadb-tls) cat prefix/etc/icinga2/features-available/icingadb.conf
object IcingaDB "icingadb" {
  host = "127.0.0.1"
  port = 6397
  use_tls = true
  #cert_path = "icingadb-tls/i2/issued/127.0.0.1.crt"
  #key_path = "icingadb-tls/i2/private/127.0.0.1.key"
  ca_path = "icingadb-tls/i2/ca.crt"
}
➜  icinga2 git:(feature/icingadb-tls) prefix/sbin/icinga2 daemon
[2020-12-09 16:39:58 +0100] information/cli: Icinga application loader (version: v2.12.0-367-gf10375b8f)
[2020-12-09 16:39:58 +0100] information/cli: Loading configuration file(s).
[2020-12-09 16:39:58 +0100] information/ConfigItem: Committing config item(s).
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 235 CheckCommands.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 1 Endpoint.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 1 Host.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 2 HostGroups.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 12 Notifications.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 2 NotificationCommands.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 3 Zones.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 11 Services.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 3 ServiceGroups.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 3 TimePeriods.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 1 User.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 1 UserGroup.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Instantiated 1 IcingaDB.
[2020-12-09 16:39:58 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2020-12-09 16:39:58 +0100] information/ConfigObject: Restoring program state from file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2020-12-09 16:39:58 +0100] information/ConfigObject: Restored 281 objects. Loaded 0 new objects without state.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Triggering Start signal for config items
[2020-12-09 16:39:58 +0100] information/FileLogger: 'main-log' started.
[2020-12-09 16:39:58 +0100] information/IcingaDB: 'icingadb' started.
[2020-12-09 16:39:58 +0100] information/IcingaDB: Trying to connect to Redis server (async, TLS) on host '127.0.0.1:6397'
[2020-12-09 16:39:58 +0100] information/NotificationComponent: 'notification' started.
[2020-12-09 16:39:58 +0100] information/ConfigItem: Activated all objects.
[2020-12-09 16:39:58 +0100] critical/IcingaDB: Cannot connect to 127.0.0.1:6397: TLS certificate validation failed: code 21: unable to verify the first certificate
^C[2020-12-09 16:40:02 +0100] information/Application: Received request to shut down.
[2020-12-09 16:40:02 +0100] information/Application: Shutting down...
[2020-12-09 16:40:02 +0100] information/NotificationComponent: 'notification' stopped.
[2020-12-09 16:40:02 +0100] information/IcingaDB: 'icingadb' stopped.
[2020-12-09 16:40:02 +0100] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2020-12-09 16:40:02 +0100] information/IcingaApplication: Icinga has shut down.
➜  icinga2 git:(feature/icingadb-tls)
```

```
➜  ic [...]

2021-06-07 13:59 UTC, julianbrost requested changes
This duplicates quite some code from `ApiListener` (min version, handshake timeout). We should try to avoid this so that these don't diverge and updating TLS stuff has to be done in multiple places. If we'd do it like this, #8718 and #8769 or this PR (depending on the order of merges) would need updating. Even if we remember to do it there, it will probably be forgotten in the future.

2021-06-08 11:25 UTC, Al2Klimov commented
## Blocked by

* [ ] #8718
* [ ] #8769

2021-07-13 12:38 UTC, Al2Klimov commented
Well, the API listener and Icinga DB work a bit different there, don’t they?

2021-07-13 12:48 UTC, julianbrost commented
In which sense? Like sure, they provide different functionality, but still, both establish outgoing TLS connection, so that's quite common functionality.

Also, I think we should learn from what lead to #8769 and not implement a timeout for just the TLS handshake but from before we attempt to connect until the connection is in a state where we can start sending Redis commands.

2021-07-13 15:25 UTC, Al2Klimov commented
Will (now) continue with an overall timeout as separate construction area.

2021-07-13 15:31 UTC, Al2Klimov commented
Once approved, please let Eric review, especially:

https://github.com/Icinga/icinga2/blob/cf15b1c52f925865bf9bc3668444fa7a8af1a4cb/lib/icingadb/redisconnection.cpp#L266-L279

2021-07-16 14:04 UTC, julianbrost requested changes

2021-07-16 14:04 UTC, julianbrost commented on lib/icingadb/redisconnection.cpp
> +						}
I'm pretty sure OpenSSL provides better APIs for validating certificates than this. This completely ignores subject alternative names and wildcards.

2021-07-16 16:33 UTC, Al2Klimov commented on lib/icingadb/icingadb.cpp
> +	}
This _is_ the config validation.

2021-07-16 16:33 UTC, Al2Klimov commented on lib/icingadb/icingadb.cpp
> +	}
1. Yes.
2. Theoretically yes, but see also #8894.

2021-07-19 07:52 UTC, julianbrost commented on lib/icingadb/icingadb.cpp
> +	}
But it's not done when `icinga2 daemon -C` is run. This should go into `IcingaDB::Validate()`, like it's already done in `Notification::Validate()` for example.

2021-07-19 11:32 UTC, julianbrost requested changes
In addition to the comments in this review: https://github.com/Icinga/icinga2/pull/8544#discussion_r672068370

2021-07-19 11:32 UTC, julianbrost commented on lib/base/tlsutility.cpp
> +	String caPath, String crlPath, String cipherList, String protocolmin, DebugInfo di)
There's already another function using the same name in this file: https://github.com/Icinga/icinga2/blob/9e5be6ad9db319e9c51fb7e5933e4b58336c66bc/lib/base/tlsutility.cpp#L73

2021-07-19 11:32 UTC, julianbrost commented on lib/icingadb/icingadb.ti
> +#include "remote/apilistener.hpp"
No longer needed, should include `tlsutility.hpp` instead now.

2021-07-19 11:32 UTC, julianbrost commented on lib/icingadb/redisconnection.cpp
> +					}
Do we really only want to do this if a CA is explicitly specified? I'd hope OpenSSL would use the system trust store by default (would have to check that, possibly `AsioTlsStream` changes this) which should be a fine default.

@lippserd Any opinions on this? Given that there are also discussions on how to handle TLS elsewhere (notably Web), I think we should decide on what new behavior we want and write all new code consistent with that.

2021-07-19 11:32 UTC, julianbrost commented on lib/icingadb/redisconnection.cpp
> +						}
Does this check still do anything useful?

2021-07-20 12:10 UTC, Al2Klimov commented on lib/icingadb/redisconnection.cpp
> +						}
Any doubts on this?

2021-07-20 12:20 UTC, julianbrost commented on lib/icingadb/redisconnection.cpp
> +						}
I don't think that it will break stuff, but
1. OpenSSL should handle if there was no certificate.
2. Is it even possible to have this case on the client side of a TLS connection? Like we're not doing TLS-PSK here, so is it even possible to complete a TLS handshake without a server certificate?

2021-07-20 13:31 UTC, Al2Klimov commented on lib/icingadb/redisconnection.cpp
> +						}
Even if I couldn’t produce an exploit, it doesn’t mean it doesn’t exist.

Consider this an airbag.

2021-07-21 10:00 UTC, julianbrost requested changes
There now also is a merge conflict to be resolved.

2021-07-21 12:10 UTC, Al2Klimov commented on lib/icingadb/icingadb.ti
> +	};
May anything else be insecure in this context? Isn’t this attribute documented well enough?

2021-07-21 12:33 UTC, julianbrost commented on lib/icingadb/icingadb.ti
> +	};
I think it's a feature if the configuration is self-describing without having to refer to the documentation each time.

2021-07-21 12:36 UTC, julianbrost requested changes
Please have a look at the build failures in the CI

2021-07-21 13:41 UTC, Al2Klimov commented on lib/icingadb/icingadb.ti
> +	};
Depending on the (missing) answer on my first question you haven’t to refer to the documentation each time.

2021-07-21 13:54 UTC, julianbrost commented on lib/icingadb/icingadb.ti
> +	};
I don't know if there's something else. I'm sure you could come up with something. Like for example allowing non-local connections with a password or something like that. But I don't think that's the point here. Think of someone looking at a config that says `insecure = yes` vs one that says `tls_insecure_skip_verify = yes`. I think the user looking at the second one will have an easier time understanding what this is doing.

2021-07-22 08:58 UTC, julianbrost requested changes
And we have yet another merge conflict that wants to be resolved unfortunately.

2021-07-22 10:07 UTC, julianbrost reviewed
One thing I noticed so far: when using a self-signed certificate for Redis and specifying it as CA, certificate validation fails with `critical/IcingaDB: Cannot connect to redis-tls:6379: TLS certificate validation failed: code 21: unable to verify the first certificate` if the certificate has the X509v3 Basic Constraints CA:FALSE set.

This behavior differs from how example `redis-cli --tls --cacert cert.pem` behaves and I think it would be nice if this also worked in Icinga to ease configuring TLS.

Also, when using `openssl verify`, that certificate passes validation:

```
$ openssl x509 -in cert-with-ca-flag.pem -text | grep CA:
                CA:TRUE
$ openssl verify -CAfile cert-with-ca-flag.pem cert-with-ca-flag.pem 
cert-with-ca-flag.pem: OK
$ openssl x509 -in cert-without-ca-flag.pem -text | grep CA:         
                CA:FALSE
$ openssl verify -CAfile cert-without-ca-flag.pem cert-without-ca-flag.pem 
cert-without-ca-flag.pem: OK
```

2021-07-22 10:12 UTC, Al2Klimov commented
Excuse me... a hypothetical user which has full control of their newly generated self-signed certificate generates it w/ CA:FALSE and... specifies it as CA?

2021-07-22 10:24 UTC, julianbrost commented
Yes. Passing as the CA parameter probably isn't the best naming here but the intention is "trust exactly this certificate".

And as I said, the behavior of this PR is inconsistent with multiple other tools, including OpenSSL itself, see also:
```
$ openssl s_client -connect self-signed.badssl.com:443 -showcerts < /dev/null > cert.pem
[...]
verify error:num=18:self signed certificate
[...]
$ openssl x509 -in cert.pem -text -noout
[...]
        Issuer: C = US, ST = California, L = San Francisco, O = BadSSL, CN = *.badssl.com
[...]
        Subject: C = US, ST = California, L = San Francisco, O = BadSSL, CN = *.badssl.com
[...]
            X509v3 Basic Constraints: 
                CA:FALSE
[...]
$ openssl s_client -connect self-signed.badssl.com:443 -CAfile cert.pem < /dev/null
[...]
Verification: OK
[...]
```

2021-07-22 10:27 UTC, Al2Klimov commented
But this kind of fault tolerance applies only to self-signed (I hope)?

2021-07-22 10:32 UTC, julianbrost commented
What do you mean? My understanding here is the following: any certificate given in the CA file is trusted. If it has CA:TRUE set, it may additionally designate other certificates as trusted by signing them.

Given that this is the default behavior of OpenSSL, I was kind of surprised that this didn't just work, so Icinga probably sets some option that changes this.

2021-07-22 10:35 UTC, Al2Klimov commented
I’m afraid _default behavior of OpenSSL CLI w/o any flags_ != _default behavior of OpenSSL C lib w/o any flags_.

2021-07-22 10:42 UTC, Al2Klimov commented
Oh, and... it's a bug. :) openssl/openssl#5236

2021-07-22 10:49 UTC, julianbrost commented
That bug describes that OpenSSL accepted **another** certificate that was signed by a certificate with CA:FALSE, that's not the case here.

2021-07-22 12:08 UTC, julianbrost requested changes
Regarding self-signed non-CA certificate as trust anchor (https://github.com/Icinga/icinga2/pull/8544#pullrequestreview-712569306): I'd say it would be pretty nice if that worked but is not absolutely required.

2021-07-23 10:26 UTC, julianbrost reviewed
Looks fine to me in general but the test protocol in https://github.com/Icinga/icinga2/pull/8544#issuecomment-741868554 is now outdated and no longer reflects current option names and verification behavior. Can you please redo this? (Shouldn't hurt to have this tested twice.)

### Expired certificate
```
object IcingaDB "icingadb-tls" {
  host = "expired.badssl.com"
  port = 443
  enable_tls = true
}
```
```
[2021-07-23 12:01:29 +0200] critical/IcingaDB: Cannot connect to expired.badssl.com:443: TLS certificate validation failed: code 10: certificate has expired
```

### Hostname mismatch
```
object IcingaDB "icingadb-tls" {
  host = "wrong.host.badssl.com"
  port = 443
  enable_tls = true
}
```
```
[2021-07-23 12:02:41 +0200] critical/IcingaDB: Cannot connect to wrong.host.badssl.com:443: TLS certificate validation failed: code 62: Hostname mismatch
```

### Untrusted self-signed certificate
```
object IcingaDB "icingadb-tls" {
  host = "self-signed.badssl.com"
  port = 443
  enable_tls = true
}
```
```
[2021-07-23 12:03:41 +0200] critical/IcingaDB: Cannot connect to self-signed.badssl.com:443: TLS certificate validation failed: code 18: self signed certificate
```

### Untrusted root
```
object IcingaDB "icingadb-tls" {
  host = "untrusted-root.badssl.com"
  port = 443
  enable_tls = true
}
```
```
[2021-07-23 12:04:34 +0200] critical/IcingaDB: Cannot connect to untrusted-root.badssl.com:443: TLS certificate validation failed: code 19: self signed certificate in certificate chain
```

### Proper certificate with custom CA
```
object IcingaDB "icingadb-tls" {
  host = "redis-tls"
  port = 6379
  enable_tls = true
  ca_path = "/data/redis-tls.cert.pem"
}
```
```
[2021-07-23 12:06:56 +0200] information/IcingaDB: Trying to connect to Redis server (async, TLS) on host 'redis-tls:6379'
[2021-07-23 12:06:56 +0200] information/IcingaDB: Connected to Redis server
```

### Trusted certificate with system trust store
```
object IcingaDB "icingadb-tls" {
  host = "icinga.com"
  port = 443 
  enable_tls = true
}
```
```
[2021-07-23 12:11:27 +0200] information/IcingaDB: Trying to connect to Redis server (async, TLS) on host 'icinga.com:443'
[2021-07-23 12:11:27 +0200] information/IcingaDB: Connected to Redis server
```
(Of course everything breaks afterwards as this is not a Redis server, but TLS is fine.)

2021-07-26 12:06 UTC, Al2Klimov commented
## Test protocol

This PR + #8932.

### Poor man's TLS

```
docker run --rm -itp 6397:6380 -v "$(pwd)/icingadb-tls:/pki:ro" redis:alpine redis-server --tls-port 6380 --tls-cert-file /pki/rd/issued/127.0.0.1.crt --tls-key-file /pki/rd/private/127.0.0.1.key --tls-ca-cert-file /pki/i2/ca.crt --tls-auth-clients no
```

```
➜  icinga2 git:(feature/icingadb-tls) cat prefix/etc/icinga2/features-available/icingadb.conf
object IcingaDB "icingadb" {
  host = "127.0.0.1"
  port = 6397
  enable_tls = true
  insecure_noverify = true
  #cert_path = "icingadb-tls/i2/issued/127.0.0.1.crt"
  #key_path = "icingadb-tls/i2/private/127.0.0.1.key"
  #ca_path = "icingadb-tls/rd/ca.crt"
}
➜  icinga2 git:(feature/icingadb-tls) prefix/sbin/icinga2 daemon
[2021-07-26 13:19:32 +0200] information/cli: Icinga application loader (version: v2.12.0-778-gd1561fb37)
[2021-07-26 13:19:32 +0200] information/cli: Loading configuration file(s).
[2021-07-26 13:19:32 +0200] information/ConfigItem: Committing config item(s).
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 244 CheckCommands.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 1 Endpoint.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 1 Host.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 2 HostGroups.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 12 Notifications.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 2 NotificationCommands.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 3 Zones.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 11 Services.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 3 ServiceGroups.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 3 TimePeriods.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 1 User.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 1 UserGroup.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2021-07-26 13:19:32 +0200] information/ConfigItem: Instantiated 1 IcingaDB.
[2021-07-26 13:19:32 +0200] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2021-07-26 13:19:32 +0200] information/ConfigItem: Triggering Start signal for config items
[2021-07-26 13:19:32 +0200] information/FileLogger: 'main-log' started.
[2021-07-26 13:19:32 +0200] information/IcingaDB: 'icingadb' started.
[2021-07-26 13:19:33 +0200] information/IcingaDB: Trying to connect to Redis server (async, TLS) on host '127.0.0.1:6397'
[2021-07-26 13:19:33 +0200] information/NotificationComponent: 'notification' started.
[2021-07-26 13:19:33 +0200] information/CheckerComponent: 'checker' started.
[2021-07-26 13:19:33 +0200] information/ConfigItem: Activated all objects.
[2021-07-26 13:19:33 +0200] information/IcingaDB: Connected to Redis server
[2021-07-26 13:19:33 +0200] information/IcingaDB: Starting initial config/status dump
[2021-07-26 13:19:33 +0200] information/IcingaDB: Initial config/status dump finished in 0.223913 seconds.
^C[2021-07-26 13:19:36 +0200] information/Application: Received request to shut down.
[2021-07-26 13:19:37 +0200] information/Application: Shutting down...
[2021-07-26 13:19:37 +0200] information/CheckerComponent: 'checker' stopped.
[2021-07-26 13:19:37 +0200] information/NotificationComponent: 'notification' stopped.
[2021-07-26 13:19:37 +0200] information/IcingaDB: 'icingadb' stopped.
[2021-07-26 13:19:37 +0200] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2021-07-26 13:19:37 +0200] information/IcingaApplication: Icinga has shut down.
➜  icinga2 git:(feature/icingadb-tls)
```

### Server authn

```
docker run --rm -itp 6397:6380 -v "$(pwd)/icingadb-tls:/pki:ro" redis:alpine redis-server --tls-port 6380 --tls-cert-file /pki/rd/issued/127.0.0.1.crt --tls-key-file /pki/rd/private/127.0.0.1.key --tls-ca-cert-file /pki/i2/ca.crt --tls-auth-clients no
```

```
➜  icinga2 git:(feature/icingadb-tls) cat prefix/etc/icinga2/features-available/icingadb.conf
object IcingaDB "icingadb" {
  host = "127.0.0.1"
  port = 6397
  enable_tls = true
  #insecure_noverify = true
  #cert_path = "icingadb-tls/i2/issued/127.0.0.1.crt"
  #key_path = "icingadb-tls/i2/private/127.0.0.1.key"
  ca_path = "icingadb-tls/rd/ca.crt"
}
➜  icinga2 git:(feature/icingadb-tls) prefix/sbin/icinga2 daemon
[2021-07-26 13:23:56 +0200] information/cli: Icinga application loader (version: v2.12.0-778-gd1561fb37)
[2021-07-26 13:23:56 +0200] information/cli: Loading configuration file(s).
[2021-07-26 13:23:56 +0200] information/ConfigItem: Committing config item(s).
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 244 CheckCommands.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 1 Endpoint.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 1 Host.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 2 HostGroups.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 12 Notifications.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 2 NotificationCommands.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 3 Zones.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 11 Services.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 3 ServiceGroups.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 3 TimePeriods.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 1 User.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 1 UserGroup.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Instantiated 1 IcingaDB.
[2021-07-26 13:23:56 +0200] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2021-07-26 13:23:56 +0200] information/ConfigObject: Restoring program state from file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2021-07-26 13:23:56 +0200] information/ConfigObject: Restored 291 objects. Loaded 0 new objects without state.
[2021-07-26 13:23:56 +0200] information/ConfigItem: Triggering Start signal for config items
[2021-07-26 13:23:56 +0200] information/FileLogger: 'main-log' started.
[2021-07-26 13:23:56 +0200] information/IcingaDB: 'icingadb' started.
[2021-07-26 13:23:57 +0200] information/NotificationComponent: 'notification' started.
[2021-07-26 13:23:57 +0200] information/CheckerComponent: 'checker' started.
[2021-07-26 13:23:57 +0200] information/IcingaDB: Trying to connect to Redis server (async, TLS) on host '127.0.0.1:6397'
[2021-07-26 13:23:57 +0200] information/ConfigItem: Activated all objects.
[2021-07-26 13:23:57 +0200] information/IcingaDB: Connected to Redis server
[2021-07-26 13:23:57 +0200] information/IcingaDB: Starting initial config/status dump
[2021-07-26 13:23:57 +0200] information/Checkable: Checkable 'Alexanders-MacBook-Pro.local' has 1 notification(s). Checking filters for type 'Problem', sends will be logged.
[2021-07-26 13:23:57 +0200] information/Notification: Sending 'Problem' notification 'Alexanders-MacB [...]

2021-07-26 13:04 UTC, julianbrost approved these changes

2021-07-26 13:50 UTC, merged