Ido*sqlConnection#InternalDeactivateObject(): mark object inactive also in memory
Icinga/icinga2 pull request #8626
Opened 2021-02-08 15:43 UTC by Al2Klimov

fixes #8584

2021-02-08 15:55 UTC, Al2Klimov commented
## Before

![Bildschirmfoto 2021-02-08 um 11 24 05](https://user-images.githubusercontent.com/6053266/107243998-d5ebb900-6a2d-11eb-8ba1-6e9a91430f28.png)
![Bildschirmfoto 2021-02-08 um 11 25 24](https://user-images.githubusercontent.com/6053266/107243992-d5532280-6a2d-11eb-851d-98efdca9b6ca.png)
![Bildschirmfoto 2021-02-08 um 11 25 34](https://user-images.githubusercontent.com/6053266/107243987-d5532280-6a2d-11eb-890c-13a47b0d9cb7.png)
![Bildschirmfoto 2021-02-08 um 11 26 42](https://user-images.githubusercontent.com/6053266/107243986-d4ba8c00-6a2d-11eb-859f-af17d71fe9d4.png)
![Bildschirmfoto 2021-02-08 um 11 26 58](https://user-images.githubusercontent.com/6053266/107243985-d421f580-6a2d-11eb-8dd1-1e06e5dfafdf.png)
![Bildschirmfoto 2021-02-08 um 11 31 02](https://user-images.githubusercontent.com/6053266/107243981-d2f0c880-6a2d-11eb-9368-dea872de7ac3.png)
![Bildschirmfoto 2021-02-08 um 11 31 09](https://user-images.githubusercontent.com/6053266/107243979-d2f0c880-6a2d-11eb-8135-e070a1205d71.png)

## After

![Bildschirmfoto 2021-02-08 um 16 38 17](https://user-images.githubusercontent.com/6053266/107243974-d2583200-6a2d-11eb-952d-03de29ad8056.png)
![Bildschirmfoto 2021-02-08 um 16 39 10](https://user-images.githubusercontent.com/6053266/107243971-d1bf9b80-6a2d-11eb-9ac2-335e289e6211.png)
![Bildschirmfoto 2021-02-08 um 16 39 26](https://user-images.githubusercontent.com/6053266/107243968-d1270500-6a2d-11eb-976e-0fe49d189b4d.png)
![Bildschirmfoto 2021-02-08 um 16 39 48](https://user-images.githubusercontent.com/6053266/107243965-d08e6e80-6a2d-11eb-8066-b4703c6fef3e.png)
![Bildschirmfoto 2021-02-08 um 16 39 55](https://user-images.githubusercontent.com/6053266/107243959-cff5d800-6a2d-11eb-978e-63d0fb9fe46f.png)
<img width="682" alt="Bildschirmfoto 2021-02-08 um 16 40 22" src="https://user-images.githubusercontent.com/6053266/107243952-cf5d4180-6a2d-11eb-8115-5e6d877a9d9d.png">
![Bildschirmfoto 2021-02-08 um 16 40 27](https://user-images.githubusercontent.com/6053266/107243945-cd937e00-6a2d-11eb-8923-e87550e0c9d3.png)

2021-02-16 16:55 UTC, julianbrost commented
I've found how to reliably trigger this issue using only using the API (tested against 2.12.3). The key is that the host has to exist in the database when Icinga starts (or to be more precise: when Icinga (re)connects to the database).

1. Create a host: `curl -skSu root:icinga -H 'Accept: application/json' -X PUT https://127.0.0.1:5665/v1/objects/hosts/host-8584 -d '{"attrs":{"check_command":"dummy"}}'`
2. Restart Icinga 2: `curl -skSu root:icinga -H 'Accept: application/json' -X POST https://localhost:5665/v1/actions/restart-process`
3. Delete the host: `curl -skSu root:icinga -H 'Accept: application/json' -X DELETE https://localhost:5665/v1/objects/hosts/host-8584`
4. Recreate the same host: `curl -skSu root:icinga -H 'Accept: application/json' -X PUT https://127.0.0.1:5665/v1/objects/hosts/host-8584 -d '{"attrs":{"check_command":"dummy"}}'`

Other insights when investigating this: `DbConnection::SetObjectActive()` is only ever called in `Ido{My,Pg}sqlConnection::Reconnect()` (before this PR), so `DbConnection::GetObjectActive()` always reflects the state when establishing the DB connection, not considering any runtime updates.

This only results in a problem when activating objects, as there it is checked whether the object is considered to be active, while when deactivating an objects, this is already ignored: https://github.com/Icinga/icinga2/blob/aa4f53009e4cfc5b45eb43919e300f386d440ada/lib/db_ido/dbconnection.cpp#L447-L475

So this PR fixes the issue but I think it can still be improved, either:
1. fix the in-memory set of active objects to always reflect the state in the database (with the current PR, the set contains all that were active when connecting to the DB minus those that were deactivated after that, even though they could have been reactivated)
2. get rid of this in-memory set altogether, it is only used to optimize away a single `UPDATE icinga_objects SET is_active = 1 WHERE object_id = ...` where this optimization isn't even done when deactivating objects (i.e. the same query with `SET is_active = 0`)

2021-06-21 12:22 UTC, julianbrost requested changes
see https://github.com/Icinga/icinga2/pull/8626#issuecomment-779970234

2021-06-28 14:47 UTC, julianbrost commented
Would adding `SetObjectActive(dbobj, true);` in the appropriate places be really so much more complex that you want to avoid it? I think this should be fairly easy and then we have a consistent state here instead of some still half-broken set.

(Upon closer consideration, option 2 would probably need a bit more evaluation whether running a noop update query on each object on startup would hurt performance too much.)

2021-07-01 11:36 UTC, julianbrost approved these changes
The current state was deemed good enough for IDO.

2021-07-02 14:34 UTC, merged