Downtime#Start(): trigger fixed downtimes immediately instead of waiting for the timer
Icinga/icinga2 pull request #8646
Opened 2021-02-22 17:28 UTC by Al2Klimov

... not to cause e.g. notifications if a problem occurs
between the downtime start time and the timer routine.

ref/IP/31129

2021-02-22 17:28 UTC, Al2Klimov commented
## Before

```
➜  icinga2 git:(master) prefix/sbin/icinga2 api setup -x critical
Enabling feature api. Make sure to restart Icinga 2 for these changes to take effect.
Done.

Now restart your Icinga 2 daemon to finish the installation!

➜  icinga2 git:(master) perl -pi -e 's/\bpassword = ".*?"/password = "123456"/' prefix/etc/icinga2/conf.d/api-users.conf
➜  icinga2 git:(master) rm prefix/etc/icinga2/conf.d/services.conf
➜  icinga2 git:(master) cat <<EOF >prefix/etc/icinga2/conf.d/hosts.conf
object Host NodeName {
check_command = "dummy"
check_interval = 1s
}
EOF
➜  icinga2 git:(master) prefix/sbin/icinga2 daemon
[2021-02-22 18:25:16 +0100] information/cli: Icinga application loader (version: v2.12.0-506-gaa4f53009)
[2021-02-22 18:25:16 +0100] information/cli: Loading configuration file(s).
[2021-02-22 18:25:16 +0100] information/ConfigItem: Committing config item(s).
[2021-02-22 18:25:16 +0100] information/ApiListener: My API identity: Alexanders-MacBook-Pro.local
[2021-02-22 18:25:16 +0100] warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/notifications.conf: 11:1-11:45) for type 'Notification' does not match anywhere!
[2021-02-22 18:25:16 +0100] warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/notifications.conf: 23:1-23:48) for type 'Notification' does not match anywhere!
[2021-02-22 18:25:16 +0100] warning/ApplyRule: Apply rule 'backup-downtime' (in /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/downtimes.conf: 5:1-5:52) for type 'ScheduledDowntime' does not match anywhere!
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 236 CheckCommands.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 1 ApiUser.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 1 Endpoint.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 1 Host.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 2 HostGroups.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 1 IcingaApplication.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 2 NotificationCommands.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 3 Zones.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 3 ServiceGroups.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 3 TimePeriods.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 1 User.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 1 UserGroup.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 1 NotificationComponent.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2021-02-22 18:25:16 +0100] information/ScriptGlobal: Dumping variables to file '/Users/aklimov/NET/WS/icinga2/prefix/var/cache/icinga2/icinga2.vars'
[2021-02-22 18:25:16 +0100] information/ConfigItem: Triggering Start signal for config items
[2021-02-22 18:25:16 +0100] information/FileLogger: 'main-log' started.
[2021-02-22 18:25:16 +0100] information/ApiListener: 'api' started.
[2021-02-22 18:25:16 +0100] information/ApiListener: Started new listener on '[::]:5665'
[2021-02-22 18:25:16 +0100] information/NotificationComponent: 'notification' started.
[2021-02-22 18:25:16 +0100] information/CheckerComponent: 'checker' started.
[2021-02-22 18:25:16 +0100] information/ConfigItem: Activated all objects.
[2021-02-22 18:25:19 +0100] information/ApiListener: New client connection from [::ffff:127.0.0.1]:53452 (no client certificate)
[2021-02-22 18:25:19 +0100] information/ConfigObjectUtility: Created and activated object 'Alexanders-MacBook-Pro.local!ffd1126e-3beb-44e6-894f-a4b3a34034b3' of type 'Downtime'.
[2021-02-22 18:25:19 +0100] information/Downtime: Added downtime 'Alexanders-MacBook-Pro.local!ffd1126e-3beb-44e6-894f-a4b3a34034b3' between '2021-02-22 18:25:09' and '2021-02-22 18:35:29', author: 'me', fixed
[2021-02-22 18:25:19 +0100] information/HttpServerConnection: Request: POST /v1/actions/schedule-downtime?type=Host&filter=true (from [::ffff:127.0.0.1]:53452), user: root, agent: curl/7.64.1, status: OK).
[2021-02-22 18:25:19 +0100] information/HttpServerConnection: HTTP client disconnected (from [::ffff:127.0.0.1]:53452)
[2021-02-22 18:25:24 +0100] information/Downtime: Triggering downtime 'Alexanders-MacBook-Pro.local!ffd1126e-3beb-44e6-894f-a4b3a34034b3' for checkable 'Alexanders-MacBook-Pro.local'.
[2021-02-22 18:25:26 +0100] information/WorkQueue: #5 (ApiListener, RelayQueue) items: 0, rate: 0.733333/s (44/min 44/5min 44/15min);
[2021-02-22 18:25:26 +0100] information/WorkQueue: #6 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
^C[2021-02-22 18:25:28 +0100] information/Application: Received request to shut down.
[2021-02-22 18:25:28 +0100] information/Application: Shutting down...
[2021-02-22 18:25:28 +0100] information/CheckerComponent: 'checker' stopped.
[2021-02-22 18:25:28 +0100] information/NotificationComponent: 'notification' stopped.
[2021-02-22 18:25:28 +0100] information/ApiListener: 'api' stopped.
[2021-02-22 18:25:28 +0100] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2021-02-22 18:25:28 +0100] information/IcingaApplication: Icinga has shut down.
➜  icinga2 git:(master)
```

Note the delay until "Triggering downtime ..."!

## After

```
➜  icinga2 git:(bugfix/trigger-fixed-downtimes-immediately) prefix/sbin/icinga2 api setup -x critical
Enabling feature api. Make sure to restart Icinga 2 for these changes to take effect.
Done.

Now restart your Icinga 2 daemon to finish the installation!

➜  icinga2 git:(bugfix/trigger-fixed-downtimes-immediately) perl -pi -e 's/\bpassword = ".*?"/password = "123456"/' prefix/etc/icinga2/conf.d/api-users.conf
➜  icinga2 git:(bugfix/trigger-fixed-downtimes-immediately) rm prefix/etc/icinga2/conf.d/services.conf
➜  icinga2 git:(bugfix/trigger-fixed-downtimes-immediately) cat <<EOF >prefix/etc/icinga2/conf.d/hosts.conf
object Host NodeName {
check_command = "dummy"
check_interval = 1s
}
EOF
➜  icinga2 git:(bugfix/trigger-fixed-downtimes-immediately) prefix/sbin/icinga2 daemon
[2021-02-22 18:27:41 +0100] information/cli: Icinga application loader (version: v2.12.0-507-g1e75bcb6b)
[2021-02-22 18:27:41 +0100] information/cli: Loading configuration file(s).
[2021-02-22 18:27:41 +0100] information/ConfigItem: Committing config item(s).
[2021-02-22 18:27:41 +0100] information/ApiListener: My API identity: Alexanders-MacBook-Pro.local
[2021-02-22 18:27:41 +0100] warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/notifications.conf: 11:1-11:45) for type 'Notification' does not match anywhere!
[2021-02-22 18:27:41 +0100] warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/notifications.conf: 23:1-23:48) for type 'Notification' does not match anywhere!
[2021-02-22 18:27:41 +0100] warning/ApplyRule: Apply rule 'backup-downtime' (in /Users/aklimov/NET/WS/icinga2/prefix/etc/icinga2/conf.d/downtimes.conf: 5:1-5:52) for type 'ScheduledDowntime' does not match anywhere!
[2021-02-22 18:27:41 +0100] information/ConfigItem: Instantiated 1 ApiListener.
[2021-02-22 18:27:41 +0100] information/ConfigItem: Instantiated 236 CheckCommands.
[2021-02-22 18:27:41 +0100] information/ConfigItem: Instantiated 1 FileLogger.
[2021-02-22 18:27:41 +0100] information/ConfigItem: Instantiated 1 ApiUser.
[2021-02-22 18:27:41 +0100] information/ConfigItem: Instantiated 1 Endpoint.
[2021-02-22 18:27:41 +0100] information/ConfigItem: Instantiated 1 CheckerComponent.
[2021-02-22 18:27:41 +0100] information/ConfigItem: Instantiated 1 Host.
[2021-02-22 18:27:41 +010 [...]

2021-06-21 07:53 UTC, julianbrost requested changes
This breaks DOWNTIMESTART notifications for these downtimes.

For fixed downtimes, these are sent here:
https://github.com/Icinga/icinga2/blob/1e75bcb6b317a5e69bddc1ad05353fad8d9b7e4b/lib/icinga/downtime.cpp#L422-L436

However, `downtime->CanBeTriggered()` will return false if `TriggerDowntime()` was called earlier.

2021-06-23 17:28 UTC, Al2Klimov commented
And now?

2021-06-24 10:07 UTC, julianbrost approved these changes

2021-06-24 10:18 UTC, lippserd approved these changes

2021-06-24 16:12 UTC, merged