RELEASE.md: Re-provision Build Server
Icinga/icinga2 pull request #8842
Opened 2021-06-22 14:32 UTC by Al2Klimov

2021-06-22 14:33 UTC, Al2Klimov commented
## Blocked by

* [ ] #8841
* [ ] https://git.icinga.com/infra/ansible-windows-build/-/issues/1

2021-07-01 07:36 UTC, julianbrost requested changes

2021-07-01 07:36 UTC, julianbrost commented on RELEASE.md
> +There may be new build versions of other dependencies (VS, MSVC).
I don't see why this is split over two paragraphs. Sounds like a single sentence to me.

2021-07-01 07:36 UTC, julianbrost commented on RELEASE.md
> +Our CI/CD uses the latest ones automatically, but the build server doesn't.
Could be more explicit about what this refers to, as the feature of GitLab is also called CI/CD. So I'd just say "GitHub Actions" and "GitLab Runner used for building release packages".

2021-07-01 11:18 UTC, julianbrost approved these changes

2021-07-01 14:02 UTC, merged