GitHub actions: auto-cancel previous jobs for the same PR
Icinga/icinga2 pull request #8867
Opened 2021-07-02 17:34 UTC by Al2Klimov

## Backport of

* #8686
* #8858

2021-07-02 17:34 UTC, Al2Klimov commented
## Blocked by

* #8858

2021-07-05 09:32 UTC, julianbrost requested changes

2021-07-05 09:32 UTC, julianbrost commented on .github/workflows/packages.yml
> +          workflow_id: docker.yml,packages.yml
There's no docker workflow in support/2.11

2021-07-06 07:48 UTC, julianbrost approved these changes

2021-07-06 08:26 UTC, merged