ScheduledDowntime::TimerProc(): Catch exceptions to make sure other downtimes are still created
Icinga/icinga2 pull request #8871
Opened 2021-07-02 17:51 UTC by Al2Klimov

## Backport of

* #8848

2021-07-02 17:52 UTC, Al2Klimov commented
## Blocked by

* #8868

2021-07-06 10:20 UTC, julianbrost requested changes

2021-07-06 10:20 UTC, julianbrost commented on lib/icinga/scheduleddowntime.cpp
>  		if (sd->IsActive() && !sd->IsPaused())
I think you backported an old version of the PR branch, the latest one has curly braces for this if.

2021-07-06 10:36 UTC, julianbrost approved these changes

2021-07-07 08:38 UTC, merged