Checkable::NotifyDowntimeEnd(): don't send Downtime end notification unless triggered
Icinga/icinga2 pull request #8874
Opened 2021-07-05 16:08 UTC by Al2Klimov

... for fixed Downtimes as well.

2021-07-05 16:16 UTC, Al2Klimov commented
## Before

Downtime has never been in effect, but end notification is fired.

```
[2021-07-05 17:30:06 +0200] information/ApiListener: New client connection from [::ffff:127.0.0.1]:55918 (no client certificate)
[2021-07-05 17:30:06 +0200] information/ConfigObjectUtility: Created and activated object 'Alexanders-MacBook-Pro.local!1' of type 'ScheduledDowntime'.
[2021-07-05 17:30:06 +0200] information/HttpServerConnection: Request: PUT /v1/objects/scheduleddowntimes/Alexanders-MacBook-Pro.local!1 (from [::ffff:127.0.0.1]:55918), user: root, agent: curl/7.64.1, status: OK).
[2021-07-05 17:30:06 +0200] information/HttpServerConnection: HTTP client disconnected (from [::ffff:127.0.0.1]:55918)
[2021-07-05 17:31:06 +0200] information/ConfigObjectUtility: Created and activated object 'Alexanders-MacBook-Pro.local!6c365155-b889-4fae-940b-da7c05d793c8' of type 'Downtime'.
[2021-07-05 17:31:06 +0200] information/Downtime: Added downtime 'Alexanders-MacBook-Pro.local!6c365155-b889-4fae-940b-da7c05d793c8' between '2021-07-05 19:00:00' and '2021-07-05 19:30:00', author: 'me', fixed
[2021-07-05 17:31:42 +0200] information/ApiListener: New client connection from [::ffff:127.0.0.1]:55922 (no client certificate)
[2021-07-05 17:31:42 +0200] information/ConfigObjectUtility: Deleted object 'Alexanders-MacBook-Pro.local!1' of type 'ScheduledDowntime'.
[2021-07-05 17:31:42 +0200] information/HttpServerConnection: Request: DELETE /v1/objects/scheduleddowntimes/Alexanders-MacBook-Pro.local!1 (from [::ffff:127.0.0.1]:55922), user: root, agent: curl/7.64.1, status: OK).
[2021-07-05 17:31:42 +0200] information/HttpServerConnection: HTTP client disconnected (from [::ffff:127.0.0.1]:55922)
[2021-07-05 17:32:06 +0200] information/Checkable: Checkable 'Alexanders-MacBook-Pro.local' has 1 notification(s). Checking filters for type 'DowntimeEnd', sends will be logged.
[2021-07-05 17:32:06 +0200] information/Notification: Sending 'DowntimeEnd' notification 'Alexanders-MacBook-Pro.local!mail-icingaadmin' for user 'icingaadmin'
[2021-07-05 17:32:06 +0200] information/ConfigObjectUtility: Deleted object 'Alexanders-MacBook-Pro.local!6c365155-b889-4fae-940b-da7c05d793c8' of type 'Downtime'.
[2021-07-05 17:32:06 +0200] information/Notification: Completed sending 'DowntimeEnd' notification 'Alexanders-MacBook-Pro.local!mail-icingaadmin' for checkable 'Alexanders-MacBook-Pro.local' and user 'icingaadmin' using command 'mail-host-notification'.
[2021-07-05 17:32:06 +0200] information/Downtime: Removed downtime 'Alexanders-MacBook-Pro.local!6c365155-b889-4fae-940b-da7c05d793c8' from checkable 'Alexanders-MacBook-Pro.local' (Reason: expired at 2021-07-05 19:30:00 +0200).
```

## After

Downtime notification isn’t fired...

```
[2021-07-05 17:39:02 +0200] information/ApiListener: New client connection from [::ffff:127.0.0.1]:55948 (no client certificate)
[2021-07-05 17:39:02 +0200] information/ConfigObjectUtility: Created and activated object 'Alexanders-MacBook-Pro.local!1' of type 'ScheduledDowntime'.
[2021-07-05 17:39:02 +0200] information/HttpServerConnection: Request: PUT /v1/objects/scheduleddowntimes/Alexanders-MacBook-Pro.local!1 (from [::ffff:127.0.0.1]:55948), user: root, agent: curl/7.64.1, status: OK).
[2021-07-05 17:39:02 +0200] information/HttpServerConnection: HTTP client disconnected (from [::ffff:127.0.0.1]:55948)
[2021-07-05 17:39:17 +0200] information/ConfigObjectUtility: Created and activated object 'Alexanders-MacBook-Pro.local!6f3ec26e-b73a-4be1-ad1c-8519f682bbeb' of type 'Downtime'.
[2021-07-05 17:39:17 +0200] information/Downtime: Added downtime 'Alexanders-MacBook-Pro.local!6f3ec26e-b73a-4be1-ad1c-8519f682bbeb' between '2021-07-05 19:00:00' and '2021-07-05 19:30:00', author: 'me', fixed
[2021-07-05 17:39:28 +0200] information/ApiListener: New client connection from [::ffff:127.0.0.1]:55949 (no client certificate)
[2021-07-05 17:39:28 +0200] information/ConfigObjectUtility: Deleted object 'Alexanders-MacBook-Pro.local!1' of type 'ScheduledDowntime'.
[2021-07-05 17:39:28 +0200] information/HttpServerConnection: Request: DELETE /v1/objects/scheduleddowntimes/Alexanders-MacBook-Pro.local!1 (from [::ffff:127.0.0.1]:55949), user: root, agent: curl/7.64.1, status: OK).
[2021-07-05 17:39:28 +0200] information/HttpServerConnection: HTTP client disconnected (from [::ffff:127.0.0.1]:55949)
[2021-07-05 17:40:17 +0200] information/ConfigObjectUtility: Deleted object 'Alexanders-MacBook-Pro.local!6f3ec26e-b73a-4be1-ad1c-8519f682bbeb' of type 'Downtime'.
[2021-07-05 17:40:17 +0200] information/Downtime: Removed downtime 'Alexanders-MacBook-Pro.local!6f3ec26e-b73a-4be1-ad1c-8519f682bbeb' from checkable 'Alexanders-MacBook-Pro.local' (Reason: expired at 2021-07-05 19:30:00 +0200).
```

... unless the Downtime has been in effect.

```
[2021-07-05 17:44:25 +0200] information/ApiListener: New client connection from [::ffff:127.0.0.1]:55966 (no client certificate)
[2021-07-05 17:44:25 +0200] information/ConfigObjectUtility: Created and activated object 'Alexanders-MacBook-Pro.local!1' of type 'ScheduledDowntime'.
[2021-07-05 17:44:25 +0200] information/HttpServerConnection: Request: PUT /v1/objects/scheduleddowntimes/Alexanders-MacBook-Pro.local!1 (from [::ffff:127.0.0.1]:55966), user: root, agent: curl/7.64.1, status: OK).
[2021-07-05 17:44:25 +0200] information/HttpServerConnection: HTTP client disconnected (from [::ffff:127.0.0.1]:55966)
[2021-07-05 17:44:33 +0200] information/ConfigObjectUtility: Created and activated object 'Alexanders-MacBook-Pro.local!e5673f60-70fe-4ea9-8a8d-0f51e84ce71d' of type 'Downtime'.
[2021-07-05 17:44:33 +0200] information/Downtime: Added downtime 'Alexanders-MacBook-Pro.local!e5673f60-70fe-4ea9-8a8d-0f51e84ce71d' between '2021-07-05 17:50:00' and '2021-07-05 17:55:00', author: 'me', fixed
[2021-07-05 17:46:33 +0200] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2021-07-05 17:46:43 +0200] information/WorkQueue: #5 (ApiListener, RelayQueue) items: 0, rate:  0/s (0/min 12/5min 25/15min);
[2021-07-05 17:46:43 +0200] information/WorkQueue: #6 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2021-07-05 17:50:03 +0200] information/Checkable: Checkable 'Alexanders-MacBook-Pro.local' has 1 notification(s). Checking filters for type 'DowntimeStart', sends will be logged.
[2021-07-05 17:50:03 +0200] information/Notification: Sending 'DowntimeStart' notification 'Alexanders-MacBook-Pro.local!mail-icingaadmin' for user 'icingaadmin'
[2021-07-05 17:50:03 +0200] information/Downtime: Triggering downtime 'Alexanders-MacBook-Pro.local!e5673f60-70fe-4ea9-8a8d-0f51e84ce71d' for checkable 'Alexanders-MacBook-Pro.local'.
[2021-07-05 17:50:03 +0200] information/Notification: Completed sending 'DowntimeStart' notification 'Alexanders-MacBook-Pro.local!mail-icingaadmin' for checkable 'Alexanders-MacBook-Pro.local' and user 'icingaadmin' using command 'mail-host-notification'.
[2021-07-05 17:50:33 +0200] information/ConfigObjectUtility: Created and activated object 'Alexanders-MacBook-Pro.local!ecaccd9c-9d90-4fe0-b329-ff56b6adc7e8' of type 'Downtime'.
[2021-07-05 17:50:33 +0200] information/Downtime: Added downtime 'Alexanders-MacBook-Pro.local!ecaccd9c-9d90-4fe0-b329-ff56b6adc7e8' between '2021-07-12 17:50:00' and '2021-07-12 17:55:00', author: 'me', fixed
[2021-07-05 17:51:33 +0200] information/ConfigObject: Dumping program state to file '/Users/aklimov/NET/WS/icinga2/prefix/var/lib/icinga2/icinga2.state'
[2021-07-05 17:51:43 +0200] information/WorkQueue: #6 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2021-07-05 17:51:43 +0200] information/WorkQueue: #5 (ApiListener, RelayQueue) items: 0, rate:  0/s (0/min 5/5min 30/15min);
[2021-07-05 17:55:28 +0200] information/Notification: Sending reminder 'Problem' notification 'Alexanders-MacBook-Pro.local!mail-icingaadmin' for user 'icingaadmin'
[2021-07-05 17:55:28 +0200] information/Notification: Completed send [...]

2021-07-06 10:47 UTC, julianbrost requested changes
Code change itself looks good.

2021-07-06 10:47 UTC, julianbrost commented on lib/icinga/checkable.cpp
>  	/* don't send notifications for flexible downtimes which never triggered */
Comment also needs an update.

2021-07-06 10:55 UTC, N-o-X approved these changes

2021-07-06 11:32 UTC, julianbrost approved these changes

2021-07-06 18:48 UTC, lippserd approved these changes

2021-07-07 08:43 UTC, merged