Allow Icinga DB to priorize state updates
Icinga/icinga2 pull request #8915
Opened 2021-07-21 12:26 UTC by Al2Klimov

2021-07-21 12:29 UTC, Al2Klimov commented
@N-o-X Haven’t there been any reason to do the opposite ex. _we decided to do so_?

2021-07-22 07:46 UTC, N-o-X commented
I think we prioritized config because we didn't want to have the initial dump slowed down by state changes. This decision was made based on our previous concept of not reading state changes until the initial dump is done.

2021-07-22 17:39 UTC, Al2Klimov commented
## Blocked by

* #8918
* #8919

2021-07-23 12:33 UTC, Al2Klimov commented
```
➜  icinga2 git:(bugfix/icingadb-prio-state) redis-cli monitor |cut -d '"' -f 1-4
OK
1627043417.497663 [0 127.0.0.1:49775] "XADD" "icinga:stats
1627043417.498044 [0 127.0.0.1:49775] "XADD" "icinga:dump
1627043417.498069 [0 127.0.0.1:49775] "DEL" "icinga:customvar
1627043417.498082 [0 127.0.0.1:49775] "PING"
1627043417.499609 [0 127.0.0.1:49764] "DEL" "icinga:eventcommand:customvar
1627043417.499641 [0 127.0.0.1:49764] "HSCAN" "icinga:checksum:eventcommand
1627043417.499700 [0 127.0.0.1:49770] "DEL" "icinga:downtime:customvar
1627043417.499714 [0 127.0.0.1:49770] "HSCAN" "icinga:checksum:downtime
1627043417.499729 [0 127.0.0.1:49774] "DEL" "icinga:hostgroup:customvar
1627043417.499736 [0 127.0.0.1:49774] "HSCAN" "icinga:checksum:hostgroup
1627043417.499747 [0 127.0.0.1:49767] "DEL" "icinga:checkcommand:customvar
1627043417.499765 [0 127.0.0.1:49767] "HSCAN" "icinga:checksum:checkcommand
1627043417.499775 [0 127.0.0.1:49765] "DEL" "icinga:notificationcommand:customvar
1627043417.499795 [0 127.0.0.1:49765] "HSCAN" "icinga:checksum:notificationcommand
1627043417.499805 [0 127.0.0.1:49768] "DEL" "icinga:servicegroup:customvar
1627043417.499812 [0 127.0.0.1:49768] "HSCAN" "icinga:checksum:servicegroup
1627043417.499822 [0 127.0.0.1:49762] "DEL" "icinga:user:customvar
1627043417.499832 [0 127.0.0.1:49762] "HSCAN" "icinga:checksum:user
1627043417.499841 [0 127.0.0.1:49760] "DEL" "icinga:zone:customvar
1627043417.499849 [0 127.0.0.1:49760] "HSCAN" "icinga:checksum:zone
1627043417.501041 [0 127.0.0.1:49767] "MULTI"
1627043417.501071 [0 127.0.0.1:49767] "HMSET" "icinga:checkcommand:customvar
1627043417.501690 [0 127.0.0.1:49767] "HMSET" "icinga:customvar
1627043417.501875 [0 127.0.0.1:49767] "EXEC"
1627043417.501904 [0 127.0.0.1:49760] "XADD" "icinga:dump
1627043417.501928 [0 127.0.0.1:49760] "XADD" "icinga:dump
1627043417.501943 [0 127.0.0.1:49760] "PING"
1627043417.501985 [0 127.0.0.1:49765] "XADD" "icinga:dump
1627043417.502002 [0 127.0.0.1:49765] "XADD" "icinga:dump
1627043417.502013 [0 127.0.0.1:49765] "XADD" "icinga:dump
1627043417.502023 [0 127.0.0.1:49765] "XADD" "icinga:dump
1627043417.502032 [0 127.0.0.1:49765] "PING"
1627043417.502041 [0 127.0.0.1:49764] "XADD" "icinga:dump
1627043417.502053 [0 127.0.0.1:49764] "XADD" "icinga:dump
1627043417.502062 [0 127.0.0.1:49764] "XADD" "icinga:dump
1627043417.502071 [0 127.0.0.1:49764] "XADD" "icinga:dump
1627043417.502080 [0 127.0.0.1:49764] "PING"
1627043417.502087 [0 127.0.0.1:49774] "XADD" "icinga:dump
1627043417.502097 [0 127.0.0.1:49774] "XADD" "icinga:dump
1627043417.502106 [0 127.0.0.1:49774] "PING"
1627043417.502113 [0 127.0.0.1:49762] "XADD" "icinga:dump
1627043417.502123 [0 127.0.0.1:49762] "XADD" "icinga:dump
1627043417.502132 [0 127.0.0.1:49762] "XADD" "icinga:dump
1627043417.502141 [0 127.0.0.1:49762] "PING"
1627043417.502148 [0 127.0.0.1:49770] "XADD" "icinga:dump
1627043417.502157 [0 127.0.0.1:49770] "PING"
1627043417.502163 [0 127.0.0.1:49768] "XADD" "icinga:dump
1627043417.502173 [0 127.0.0.1:49768] "XADD" "icinga:dump
1627043417.502182 [0 127.0.0.1:49768] "PING"
1627043417.502316 [0 127.0.0.1:49767] "MULTI"
1627043417.504217 [0 127.0.0.1:49767] "HMSET" "icinga:checksum:checkcommand
1627043417.504316 [0 127.0.0.1:49767] "HMSET" "icinga:checkcommand
1627043417.504474 [0 127.0.0.1:49767] "EXEC"
1627043417.504479 [0 127.0.0.1:49767] "XADD" "icinga:dump
1627043417.504495 [0 127.0.0.1:49767] "XADD" "icinga:dump
1627043417.504506 [0 127.0.0.1:49767] "XADD" "icinga:dump
1627043417.504600 [0 127.0.0.1:49767] "XADD" "icinga:dump
1627043417.504622 [0 127.0.0.1:49767] "PING"
1627043417.504633 [0 127.0.0.1:49773] "DEL" "icinga:endpoint:customvar
1627043417.504647 [0 127.0.0.1:49773] "HSCAN" "icinga:checksum:endpoint
1627043417.504662 [0 127.0.0.1:49771] "DEL" "icinga:notification:customvar
1627043417.504686 [0 127.0.0.1:49771] "HSCAN" "icinga:checksum:notification
1627043417.504717 [0 127.0.0.1:49761] "DEL" "icinga:timeperiod:customvar
1627043417.504739 [0 127.0.0.1:49761] "HSCAN" "icinga:checksum:timeperiod
1627043417.504760 [0 127.0.0.1:49763] "DEL" "icinga:service:customvar
1627043417.504776 [0 127.0.0.1:49763] "HSCAN" "icinga:checksum:service
1627043417.504804 [0 127.0.0.1:49766] "DEL" "icinga:host:customvar
1627043417.504833 [0 127.0.0.1:49766] "HSCAN" "icinga:checksum:host
1627043417.504861 [0 127.0.0.1:49772] "DEL" "icinga:usergroup:customvar
1627043417.504878 [0 127.0.0.1:49772] "HSCAN" "icinga:checksum:usergroup
1627043417.505371 [0 127.0.0.1:49771] "XADD" "icinga:dump
1627043417.505610 [0 127.0.0.1:49771] "XADD" "icinga:dump
1627043417.505699 [0 127.0.0.1:49771] "XADD" "icinga:dump
1627043417.505760 [0 127.0.0.1:49771] "XADD" "icinga:dump
1627043417.505778 [0 127.0.0.1:49771] "XADD" "icinga:dump
1627043417.505793 [0 127.0.0.1:49771] "PING"
1627043417.505811 [0 127.0.0.1:49761] "XADD" "icinga:dump
1627043417.505915 [0 127.0.0.1:49761] "XADD" "icinga:dump
1627043417.505978 [0 127.0.0.1:49761] "XADD" "icinga:dump
1627043417.506004 [0 127.0.0.1:49761] "XADD" "icinga:dump
1627043417.506020 [0 127.0.0.1:49761] "XADD" "icinga:dump
1627043417.506037 [0 127.0.0.1:49761] "PING"
1627043417.506057 [0 127.0.0.1:49763] "XADD" "icinga:dump
1627043417.506072 [0 127.0.0.1:49763] "XADD" "icinga:dump
1627043417.506081 [0 127.0.0.1:49763] "XADD" "icinga:dump
1627043417.506093 [0 127.0.0.1:49763] "XADD" "icinga:dump
1627043417.506106 [0 127.0.0.1:49763] "PING"
1627043417.506116 [0 127.0.0.1:49772] "XADD" "icinga:dump
1627043417.506162 [0 127.0.0.1:49772] "XADD" "icinga:dump
1627043417.506180 [0 127.0.0.1:49772] "PING"
1627043417.506255 [0 127.0.0.1:49773] "XADD" "icinga:dump
1627043417.507082 [0 127.0.0.1:49773] "PING"
1627043417.507119 [0 127.0.0.1:49769] "DEL" "icinga:comment:customvar
1627043417.507134 [0 127.0.0.1:49769] "HSCAN" "icinga:checksum:comment
1627043417.507656 [0 127.0.0.1:49769] "XADD" "icinga:dump
1627043417.507740 [0 127.0.0.1:49769] "PING"
1627043417.607940 [0 127.0.0.1:49766] "ZADD" "icinga:nextupdate:host
1627043417.697263 [0 127.0.0.1:49766] "ZADD" "icinga:nextupdate:host
1627043417.704081 [0 127.0.0.1:49766] "ZADD" "icinga:nextupdate:host
1627043417.706823 [0 127.0.0.1:49766] "ZADD" "icinga:nextupdate:host
1627043417.712111 [0 127.0.0.1:49766] "ZADD" "icinga:nextupdate:host
1627043417.712645 [0 127.0.0.1:49766] "ZADD" "icinga:nextupdate:host
1627043417.715403 [0 127.0.0.1:49766] "ZADD" "icinga:nextupdate:host
1627043417.719761 [0 127.0.0.1:49766] "ZADD" "icinga:nextupdate:host
1627043417.720264 [0 127.0.0.1:49766] "MULTI"
1627043417.720361 [0 127.0.0.1:49775] "XADD" "icinga:runtime:state
1627043417.720519 [0 127.0.0.1:49775] "XADD" "icinga:runtime:state
1627043417.720651 [0 127.0.0.1:49775] "XADD" "icinga:history:stream:state
1627043417.720751 [0 127.0.0.1:49775] "XADD" "icinga:history:stream:state
1627043417.720849 [0 127.0.0.1:49775] "XADD" "icinga:runtime:state
1627043417.720986 [0 127.0.0.1:49775] "XADD" "icinga:runtime:state
1627043417.721121 [0 127.0.0.1:49775] "XADD" "icinga:history:stream:state
1627043417.721211 [0 127.0.0.1:49775] "XADD" "icinga:history:stream:state
1627043417.721307 [0 127.0.0.1:49775] "XADD" "icinga:runtime:state
1627043417.721437 [0 127.0.0.1:49775] "XADD" "icinga:history:stream:state
1627043417.721532 [0 127.0.0.1:49775] "XADD" "icinga:runtime:state
1627043417.721658 [0 127.0.0.1:49775] "XADD" "icinga:history:stream:state
1627043417.721748 [0 127.0.0.1:49775] "XADD" "icinga:runtime:state
1627043417.729870 [0 127.0.0.1:49775] "XADD" "icinga:history:stream:state
1627043417.729980 [0 127.0.0.1:49775] "XADD" "icinga:runtime:state
1627043417.730115 [0 127.0.0.1:49775] "XADD" "icinga:history:stream:state
1627043417.730214 [0 127.0.0.1:49775] "XADD" "icinga:runtime:state
1627043417.730338 [0 127.0.0.1:49775] "XADD" "icinga:runtime:state
1627043417.735274 [0 127.0.0.1:49775] "XADD" "icinga:runtime:state
1627043417.735431 [0 127.0.0.1:49775] "XADD" "icinga:runtime:state
1627043417.735998 [0 127.0.0.1:49775] "XADD" "icinga:runtime:state
1627043417.736446 [0 127.0.0.1:4 [...]

2021-07-23 14:12 UTC, Al2Klimov commented
At the end of the day this will in parallel:

* Sync config + initial state hash maps, **then** the runtime changes to those state maps possibly occurred while syncing config + initial state hash maps
* Stream state updates to a dedicated stream

Icinga DB will have to handle this parallelism not to flip past and future, but hey, **it’s Icinga DB's task** to write Redis->DB. 🤷‍♂️

2021-07-26 08:23 UTC, lippserd approved these changes

2021-07-26 12:17 UTC, N-o-X requested changes
LGTM, besides the little comment thing.

2021-07-26 12:17 UTC, N-o-X commented on lib/icingadb/redisconnection.hpp
> +			RuntimeStateStream, // runtime state update notifications, doesn't affect initially synced states
I'd say `notifications` isn't correct in this case, because we do not only send a notification here, but the whole state.

2021-07-26 15:11 UTC, N-o-X approved these changes

2021-07-27 18:22 UTC, merged