Adjust incosistent pki log messages
Icinga/icinga2 pull request #8965
Opened 2021-08-09 10:32 UTC by Yonas-net

Checked all the error codes and couldn't find any others that could be raised,
even though they were issued by CA, apart from the revoked CRTs.

2021-08-09 11:00 UTC, Al2Klimov requested changes

2021-08-09 11:00 UTC, Al2Klimov commented on lib/remote/jsonrpcconnection-pki.cpp
> +			} else {
Please check for `==`, not `!=`, if the if has an else branch. (I personally try to avoid double negatives as `!=` – else.)

2021-08-09 11:09 UTC, Al2Klimov commented on lib/remote/jsonrpcconnection-pki.cpp
> +			if (*openssl_code == X509_V_ERR_CERT_REVOKED) {
Are you sure that the pointer `openssl_code` is not NULL and you can just dereference it?

2021-08-09 11:28 UTC, Al2Klimov requested changes
Write a test protocol.

2021-08-09 13:28 UTC, Yonas-net commented
**Before**:
See https://github.com/Icinga/icinga2/issues/8682#issue-832191819

**After**:
```
[2021-08-09 15:26:16 +0200] information/ApiListener: New client connection for identity 'satellite' from [::ffff:127.0.0.1]:55429 (certificate validation failed: code 23: certificate revoked)
[2021-08-09 15:26:16 +0200] information/JsonRpcConnection: Received certificate request for CN 'satellite' no longer trusted: certificate revoked (code 23)
[2021-08-09 15:26:16 +0200] information/JsonRpcConnection: Certificate request for CN 'satellite' is pending. Waiting for approval.
[2021-08-09 15:26:16 +0200] warning/JsonRpcConnection: API client disconnected for identity 'satellite'
```

2021-08-09 13:42 UTC, Al2Klimov commented
> [2021-08-09 15:26:16 +0200] information/ApiListener: New client connection for identity 'satellite' from [::ffff:127.0.0.1]:55429 (certificate validation failed: code 23: certificate revoked)

And the other case?

2021-08-09 13:47 UTC, Yonas-net commented
> > [2021-08-09 15:26:16 +0200] information/ApiListener: New client connection for identity 'satellite' from [::ffff:127.0.0.1]:55429 (certificate validation failed: code 23: certificate revoked)
> 
> And the other case?

Which other case?

2021-08-09 13:58 UTC, Yonas-net commented
`X509_V_ERR_CRL_HAS_EXPIRED` ?

2021-08-09 15:01 UTC, Al2Klimov commented
Well, you've introduced an if with an else branch – two cases. One's already covered by https://github.com/Icinga/icinga2/pull/8965#issuecomment-895222963 – one not.

2021-08-09 16:26 UTC, Yonas-net commented
```

2021-08-09 16:28 UTC, Yonas-net commented
Actually, `CRL has expired` also falls under the no longer trusted flavor, doesn't it?

2021-08-10 09:18 UTC, julianbrost commented on lib/remote/jsonrpcconnection-pki.cpp
> +			}
I'd simply go with some generic wording like "not trusted"/"verification failed"/... here. Anything more specific only duplicates the error message from OpenSSL anyways and is at risk of being inconsistent with error conditions we did not explicitly consider.

2021-08-13 12:32 UTC, julianbrost requested changes
My intention was not to give suggestions for the individual cases. What I wanted to say was to not attempt using different wording depending on the error cause but instead remove that `if` altogether and use a single message in all cases.

I just didn't want to give exact wording. You also have to ensure that it fits the rest of the message, for example "Received certificate request for CN 'foo' verification failed: [...]" sounds broken.

2021-11-19 12:45 UTC, julianbrost requested changes
Now the message is "Received certificate request for CN 'something' couldn't be verified: some error message", it should rather be "which couldn't be verified" to be correct.

2021-11-22 08:20 UTC, yhabteab commented
> it should rather be "which couldn't be verified" to be correct.

Actually, I don't see any difference, but I have changed it the way you requested.

2021-11-22 08:26 UTC, julianbrost approved these changes

2021-11-22 08:28 UTC, julianbrost commented
> > it should rather be "which couldn't be verified" to be correct.
> 
> Actually, I don't see any difference, but I have changed it the way you requested.

On second thought, both versions are fine. Without "which", you have the read "received" as an adjective and not as the verb of the sentence (which I didn't in the first place).

2021-11-22 09:51 UTC, Al2Klimov commented
@cla-bot check

2021-11-22 10:08 UTC, Al2Klimov commented
What's the problem here?

2021-11-22 10:13 UTC, julianbrost commented
The account was renamed and this change is probably not yet reflected in our CLA check.

2021-11-22 13:33 UTC, lippserd commented
@cla-bot check

2021-11-22 15:06 UTC, merged