PluginUtility: Fix PerfData don't get parsed correctly
Icinga/icinga2 pull request #8969
Opened 2021-08-10 15:03 UTC by Yonas-net

The problem was that some PerfData labels contained several whitespace characters,
not just one, and therefore it was parsed incorrectly in `SplitPerfdata()`. I.e. the condition
in line 144 checks whether the first and last character is a normal quote, but since the
label can contain spaces at the beginning and at the end respectively, this caused the problems.

This PR fixes the problem by removing all occurring whitespace from the beginning and end,
before starting to parse the actual label.

2021-08-10 15:18 UTC, Al2Klimov requested changes
Write a test protocol.

2021-08-10 15:21 UTC, Al2Klimov commented
... preferably with screenshots.

2021-08-11 07:19 UTC, Yonas-net commented
**Before**:
See #8912

**After**:
**Icinga Web 2**:

<img width="1182" alt="Bildschirmfoto 2021-08-10 um 17 55 27" src="https://user-images.githubusercontent.com/57616252/128894960-6e6144df-011c-466e-bed1-b763bafdac39.png">

**Graphite**:

<img width="473" alt="Bildschirmfoto 2021-08-11 um 09 17 37" src="https://user-images.githubusercontent.com/57616252/128986403-88aee766-a5fa-4d8a-8c7f-5256db4c7024.png">


**Api**:
```bash
 "last_check_result": {
                    "active": true,
                    "check_source": "master",
                    "command": "dummy",
                    "execution_end": 1628611234.453256,
                    "execution_start": 1628611234.453256,
                    "exit_status": 0,
                    "output": "OK - 8 counters checked, 8 ok\n            [0] rpn_cap_snd_idp_sms OK - rpn_cap_snd_idp_sms: 741 \n            [1] rpn_cc_map_remote_prv_no_rsp_from_peer OK - rpn_cc_map_remote_prv_no_rsp_from_peer: 10 \n            [2] rpn_diameter_snd_acr OK - rpn_diameter_snd_acr: 9451 \n            [3] rpn_map_atsi_sent OK - rpn_map_atsi_sent: 1702 \n            [4] rpn_map_mo_fsm_rcvd OK - rpn_map_mo_fsm_rcvd: 12856 \n            [5] rpn_map_mo_fsm_sent OK - rpn_map_mo_fsm_sent: 4274 \n            [6] rpn_map_sri_sm_sent OK - rpn_map_sri_sm_sent: 12145 \n            [7] rpn_sip_rcv_msg_200 OK - rpn_sip_rcv_msg_200: 11982",
                    "performance_data": [
                        "kpi_avg_cpu_occ=37",
                        "kpi_avg_mem_util=58",
                        "kpi_mavkpi_map_sri_proc_rate_egress=99.92",
                        "kpi_sip_rate_reg-ok=100.01"
                    ],
```

2021-08-11 09:09 UTC, Al2Klimov commented
Colleagues, do you consider this a good idea?

2021-08-11 09:39 UTC, julianbrost commented
What was the service used for testing? https://github.com/Icinga/icinga2/issues/8912#issuecomment-895938876? Where do the two consecutive space characters come from?

> The problem was that some PerfData labels contained several whitespace characters

If there is one, it's fine, but if there are multiple ones, it breaks?

2021-08-11 10:39 UTC, Yonas-net commented
> What was the service used for testing? [#8912 (comment)](https://github.com/Icinga/icinga2/issues/8912#issuecomment-895938876)?

Yes.

> Where do the two consecutive space characters come from?

From `PluginUtility::ParseCheckOutput()`;

> If there is one, it's fine, but if there are multiple ones, it breaks?

Yes.
![Bildschirmfoto 2021-08-11 um 12 36 03](https://user-images.githubusercontent.com/57616252/129015299-e3e5523f-97ca-4574-9ad3-6a7e3e6d2ba4.png)

2021-08-11 10:55 UTC, Yonas-net commented
Whenever icinga2 parses the PerfData from one line to the next, such leading spaces happen. I.e let's assume we have the following plugin output, as you can see with a couple of PerfDates in different lines.

```bash
OK - 8 counters checked, 8 ok| 'kpi_avg_cpu_occ'=37 \
        [0] rpn_cap_snd_idp_sms OK - rpn_cap_snd_idp_sms: 741| 'kpi_dummy_test1'=100\
        [1] rpn_cc_map_remote_prv_no_rsp_from_peer OK - rpn_cc_map_remote_prv_no_rsp_from_peer: 10 \
        [2] rpn_diameter_snd_acr OK - rpn_diameter_snd_acr: 9451| 'kpi_dummy_test2'=100 \
        [3] rpn_map_atsi_sent OK - rpn_map_atsi_sent: 1702 \
        [4] rpn_map_mo_fsm_rcvd OK - rpn_map_mo_fsm_rcvd: 12856 \
        [5] rpn_map_mo_fsm_sent OK - rpn_map_mo_fsm_sent: 4274| 'kpi_dummy_test3'=100 \
        [6] rpn_map_sri_sm_sent OK - rpn_map_sri_sm_sent: 12145 \
        [7] rpn_sip_rcv_msg_200 OK - rpn_sip_rcv_msg_200: 11982| 'kpi_avg_mem_util'=58 'kpi_mavkpi_map_sri_proc_rate_egress'=99.92 'kpi_sip_rate_reg-ok'=100.01
```
Now when it finishes parsing the PerfData on the first line, it goes to the next line and appends additional whitespace, which is unnecessary.

2021-08-11 14:22 UTC, julianbrost requested changes
Looks like the issue can be reproduced with something very simple, why didn't anyone notice this earlier 🤨
```
vars.dummy_text = "foo | 'x'=23  'y'=42"
```

Simply using trim would now also accept something like `'x' =42`. I think we don't accept spaces after the `=` (haven't explicitly tested this but code like that should be the case), it would be better to not accept spaces in front of it as well and only remove leading spaces.

Please also add tests for this to https://github.com/Icinga/icinga2/blob/master/test/icinga-perfdata.cpp

2021-08-12 11:26 UTC, Yonas-net commented
> I think we don't accept spaces after the `=`

What do you mean we don't accept it? Well, I don't see anywhere that we explicitly don't allow it. If there should be such PerfDatas, then they are just faulty and will only be parsed as `"x="`. Do you want also that the PerfDatas which contain whitespaces before the `=` should be corrupt too or how is it meant.

2022-12-20 12:19 UTC, Al2Klimov requested changes
The pipeline failed.

2023-01-30 15:30 UTC, Al2Klimov approved these changes

2023-03-30 08:58 UTC, julianbrost commented on test/icinga-perfdata.cpp
> +BOOST_AUTO_TEST_CASE(multiline)
Test at least has to also be added to https://github.com/Icinga/icinga2/blob/e31bb2b534bf45cb830d54708a78ecd1fc88d257/test/CMakeLists.txt#L46. Apart from that, it's unclear why this is named "multiline" without a single `\n` in the test.

2023-04-05 13:48 UTC, Al2Klimov approved these changes

2023-05-11 09:42 UTC, Raupueppi commented
Is the problem in [11853](https://community.icinga.com/t/graphite-weird-folder-name/11853) fixed with this fix here?

2023-05-22 11:21 UTC, julianbrost commented
> Is the problem in [11853](https://community.icinga.com/t/graphite-weird-folder-name/11853) fixed with this fix here?

Looks very similar to the screenshot from #8912:

> ![github_issue_graphite](https://user-images.githubusercontent.com/37802318/126316432-de3d5175-83ee-4bfd-b362-2b655181bea0.png)

So probably yes.

2023-05-22 15:06 UTC, julianbrost commented
This actually has nothing to do with single quotes: this can also be reproduced with simpler values like ` a=1` (parsed as `' a'=1` without this PR) or `a=1  b=2` (parsed as `a=1 ' b'=2` without this PR).

2023-05-22 15:16 UTC, julianbrost approved these changes

2023-05-22 15:16 UTC, merged