Icinga DB: Make sure object relationships are handled correctly during runtime updates
Icinga/icinga2 pull request #9009
Opened 2021-09-22 14:57 UTC by N-o-X

2021-09-28 08:44 UTC, julianbrost reviewed
Just some intermediate feedback, not really a full review.

In addition to the inline comments, please add some explanation for the extra changes for the Notification/UserGroup relation to the PR description (why is that needed there but not elsewhere?).

2021-09-28 08:44 UTC, julianbrost commented on lib/icingadb/icingadb-objects.cpp
> +		ConfigObject::Ptr (*getGroup)(const String& name);
Doesn't seem to be used anymore?

2021-09-28 08:44 UTC, julianbrost commented on lib/icingadb/icingadb-objects.cpp
> +		auto group ((*getGroup)(groupName));
Probably just (partially) copied over but I'm not a fan of C-style function pointers. Maybe at least use `std::function<...>` as type of `getGroup` or maybe templating the function could be an option?

2021-11-08 15:53 UTC, julianbrost requested changes

2021-11-08 15:53 UTC, julianbrost commented on tools/mkclass/classcompiler.cpp
> +					m_Impl << "\t\t" << "On" << field.GetFriendlyName() << "ChangedWithOldValue(static_cast<" << klass.Name << " *>(this), oldValue, value);" << std::endl;
Yeah, we also want that check here, otherwise this is called during object activation and even `daemon -C`.

2021-11-12 16:48 UTC, julianbrost approved these changes
Tests from https://github.com/Icinga/icingadb/pull/404 pass and I did some more manual testing, so I hope this is good enough. I think I noticed a new User missing from the recipients during one test, so there could still be something, but I retried the very same operation quite a few times, so I hope I just did something wrong during that one iteration.

2021-11-12 16:52 UTC, merged

2021-11-13 22:09 UTC, dasJ commented
Is it possible this broke something when building with gcc 10/boost 1.69.0/…? Trying to update the package from 2.13.1 in Nix I get a lot of errors:
```
/build/source/lib/icinga/usergroup.cpp:79:24: error: incomplete type 'icinga::Notification' used in nested name specifier
   79 | std::set<Notification::Ptr> UserGroup::GetNotifications() const
      |                        ^~~
/build/source/lib/icinga/usergroup.cpp:79:24: error: incomplete type 'icinga::Notification' used in nested name specifier
/build/source/lib/icinga/usergroup.cpp:79:27: error: template argument 1 is invalid
   79 | std::set<Notification::Ptr> UserGroup::GetNotifications() const
      |                           ^
/build/source/lib/icinga/usergroup.cpp:79:27: error: template argument 2 is invalid
/build/source/lib/icinga/usergroup.cpp:79:27: error: template argument 3 is invalid
/build/source/lib/icinga/usergroup.cpp:79:29: error: no declaration matches 'int icinga::UserGroup::GetNotifications() const'
   79 | std::set<Notification::Ptr> UserGroup::GetNotifications() const
      |                             ^~~~~~~~~
In file included from /build/source/lib/icinga/usergroup.cpp:3:
/build/source/lib/icinga/usergroup.hpp:31:40: note: candidate is: 'std::set<boost::intrusive_ptr<icinga::Notification> > icinga::UserGroup::GetNotifications() const'
   31 |  std::set<intrusive_ptr<Notification>> GetNotifications() const;
      |                                        ^~~~~~~~~~~~~~~~
/build/source/lib/icinga/usergroup.hpp:21:7: note: 'class icinga::UserGroup' defined here
   21 | class UserGroup final : public ObjectImpl<UserGroup>
      |       ^~~~~~~~~
/build/source/lib/icinga/usergroup.cpp:85:53: error: invalid use of incomplete type 'class icinga::Notification'
   85 | void UserGroup::AddNotification(const Notification::Ptr& notification)
      |                                                     ^~~
In file included from /build/source/lib/icinga/usergroup.cpp:3:
/build/source/lib/icinga/usergroup.hpp:14:7: note: forward declaration of 'class icinga::Notification'
   14 | class Notification;
      |       ^~~~~~~~~~~~
/build/source/lib/icinga/usergroup.cpp:85:6: error: no declaration matches 'void icinga::UserGroup::AddNotification(const int&)'
   85 | void UserGroup::AddNotification(const Notification::Ptr& notification)
      |      ^~~~~~~~~
In file included from /build/source/lib/icinga/usergroup.cpp:3:
/build/source/lib/icinga/usergroup.hpp:32:7: note: candidate is: 'void icinga::UserGroup::AddNotification(const boost::intrusive_ptr<icinga::Notification>&)'
   32 |  void AddNotification(const intrusive_ptr<Notification>& notification);
      |       ^~~~~~~~~~~~~~~
/build/source/lib/icinga/usergroup.hpp:21:7: note: 'class icinga::UserGroup' defined here
   21 | class UserGroup final : public ObjectImpl<UserGroup>
      |       ^~~~~~~~~
/build/source/lib/icinga/usergroup.cpp:91:56: error: invalid use of incomplete type 'class icinga::Notification'
   91 | void UserGroup::RemoveNotification(const Notification::Ptr& notification)
      |                                                        ^~~
In file included from /build/source/lib/icinga/usergroup.cpp:3:
/build/source/lib/icinga/usergroup.hpp:14:7: note: forward declaration of 'class icinga::Notification'
   14 | class Notification;
      |       ^~~~~~~~~~~~
/build/source/lib/icinga/usergroup.cpp:91:6: error: no declaration matches 'void icinga::UserGroup::RemoveNotification(const int&)'
   91 | void UserGroup::RemoveNotification(const Notification::Ptr& notification)
      |      ^~~~~~~~~
In file included from /build/source/lib/icinga/usergroup.cpp:3:
/build/source/lib/icinga/usergroup.hpp:33:7: note: candidate is: 'void icinga::UserGroup::RemoveNotification(const boost::intrusive_ptr<icinga::Notification>&)'
   33 |  void RemoveNotification(const intrusive_ptr<Notification>& notification);
      |       ^~~~~~~~~~~~~~~~~~
/build/source/lib/icinga/usergroup.hpp:21:7: note: 'class icinga::UserGroup' defined here
   21 | class UserGroup final : public ObjectImpl<UserGroup>
      |       ^~~~~~~~~
In file included from /build/source/lib/base/object.hpp:8,
                 from /build/source/build/lib/icinga/usergroup-ti.hpp:4,
                 from /build/source/lib/icinga/usergroup.hpp:7,
                 from /build/source/lib/icinga/usergroup.cpp:3:
include/boost/smart_ptr/intrusive_ptr.hpp: In instantiation of 'boost::intrusive_ptr<T>::~intrusive_ptr() [with T = icinga::Notification]':
/nix/store/gbaf9hcffnrblpj7qv5lsrkcvjny08cc-gcc-10.3.0/include/c++/10.3.0/ext/new_allocator.h:156:13:   required from 'void __gnu_cxx::new_allocator<_Tp>::destroy(_Up*) [with _Up = boost::intrusive_ptr<icinga::Notification>; _Tp = std::_Rb
_tree_node<boost::intrusive_ptr<icinga::Notification> >]'
/nix/store/gbaf9hcffnrblpj7qv5lsrkcvjny08cc-gcc-10.3.0/include/c++/10.3.0/bits/alloc_traits.h:531:15:   required from 'static void std::allocator_traits<std::allocator<_CharT> >::destroy(std::allocator_traits<std::allocator<_CharT> >::allo
cator_type&, _Up*) [with _Up = boost::intrusive_ptr<icinga::Notification>; _Tp = std::_Rb_tree_node<boost::intrusive_ptr<icinga::Notification> >; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<std::_Rb_tree
_node<boost::intrusive_ptr<icinga::Notification> > >]'
/nix/store/gbaf9hcffnrblpj7qv5lsrkcvjny08cc-gcc-10.3.0/include/c++/10.3.0/bits/stl_tree.h:646:24:   required from 'void std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_destroy_node(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compa
re, _Alloc>::_Link_type) [with _Key = boost::intrusive_ptr<icinga::Notification>; _Val = boost::intrusive_ptr<icinga::Notification>; _KeyOfValue = std::_Identity<boost::intrusive_ptr<icinga::Notification> >; _Compare = std::less<boost::int
rusive_ptr<icinga::Notification> >; _Alloc = std::allocator<boost::intrusive_ptr<icinga::Notification> >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type = std::_Rb_tree_node<boost::intrusive_ptr<icinga::Notification>
>*]'
/nix/store/gbaf9hcffnrblpj7qv5lsrkcvjny08cc-gcc-10.3.0/include/c++/10.3.0/bits/stl_tree.h:654:2:   required from 'void std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_drop_node(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare,
_Alloc>::_Link_type) [with _Key = boost::intrusive_ptr<icinga::Notification>; _Val = boost::intrusive_ptr<icinga::Notification>; _KeyOfValue = std::_Identity<boost::intrusive_ptr<icinga::Notification> >; _Compare = std::less<boost::intrusi
ve_ptr<icinga::Notification> >; _Alloc = std::allocator<boost::intrusive_ptr<icinga::Notification> >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type = std::_Rb_tree_node<boost::intrusive_ptr<icinga::Notification> >*]'
/nix/store/gbaf9hcffnrblpj7qv5lsrkcvjny08cc-gcc-10.3.0/include/c++/10.3.0/bits/stl_tree.h:1921:4:   required from 'void std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_erase(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Al
loc>::_Link_type) [with _Key = boost::intrusive_ptr<icinga::Notification>; _Val = boost::intrusive_ptr<icinga::Notification>; _KeyOfValue = std::_Identity<boost::intrusive_ptr<icinga::Notification> >; _Compare = std::less<boost::intrusive_
ptr<icinga::Notification> >; _Alloc = std::allocator<boost::intrusive_ptr<icinga::Notification> >; std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_Link_type = std::_Rb_tree_node<boost::intrusive_ptr<icinga::Notification> >*]'
/nix/store/gbaf9hcffnrblpj7qv5lsrkcvjny08cc-gcc-10.3.0/include/c++/10.3.0/bits/stl_tree.h:991:9:   required from 'std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::~_Rb_tree() [with _Key = boost::intrusive_ptr<icinga::Notification>
; _Val = boost::intrusive_ptr<icinga::Notification>; _KeyOfValue = std::_Identity<boost::intrusive_ptr<icinga::Notification> >; _Compare = std::less<boost::intrusive_ptr<icinga::Notification> >; _Alloc = std::allocator<boost::intrusive_ptr
<icinga::Notification> > [...]

2021-11-17 08:58 UTC, julianbrost commented
I was able to reproduce this with GCC 11.1.0 and Boost 1.69. Do you use the `ICINGA2_UNITY_BUILD` CMake variable? If not, you could try if `-DICINGA2_UNITY_BUILD=ON` works as a workaround for now.

2021-11-17 11:07 UTC, dasJ commented
Thank you, I had disabled unit build to get a better progress indicator from cmake but [re-enabling it](https://github.com/NixOS/nixpkgs/pull/146379/files) works around this problem :)