pass nwc_health check SNMPv3 args only if needed
Icinga/icinga2 pull request #9095
Opened 2021-11-19 16:34 UTC by orbison

The `check_nwc_health` plugin fails if any of its SNMPv3 arguments were passed but
the SNMP version 3 protocol was not requested. This poses a problem for instance 
if the SNMPv3 nwc_health arguments were inherited from some template but the host
supports SNMPv1 or SNMPv2c only.

The following works:

```
	check_nwc_health --hostname 192.0.2.3 --mode cpu-load \
		--protocol 1 --community public
```
But the following plugin invocation results in an error:

```
	check_nwc_health --hostname 192.0.2.3 --mode cpu-load \
		--protocol 1 --community public \
		--username joe --authpassword xxx
```
This PR makes rendering of all SNMPv3 plugin arguments conditional and based on the presence of `--protocol 3` argument. This also results in a cleaner command line when
inspecting the command invocation through the _Inspect_ link in the Icinga Web interface.

2021-11-19 17:04 UTC, orbison commented
Hi there,

FYI, I've just signed the CLA.

Cheers,

Rostislav


On 19. 11. 21 17:52, cla-bot[bot] wrote:
>
> Thank you for your pull request. Before we can look at it, you'll need 
> to sign a Contributor License Agreement (CLA).
>
> *Please follow instructions at 
> https://icinga.com/company/contributor-agreement 
> <https://icinga.com/company/contributor-agreement> to sign the CLA.*
>
> After that, please reply here with a comment and we'll verify.
>
> Contributors that have not signed yet: @orbison 
> <https://github.com/orbison>
>
>  *
>
>     If you've already signed a CLA, it's possible we don't have your
>     GitHub username or you're using a different email address. Please
>     contact us <https://icinga.com/company/contact/> if you think this
>     is the case.
>
>  *
>
>     If you signed the CLA as a corporation, your GitHub username may
>     not have been submitted to us. Please reach out to the responsible
>     person in your organization.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/Icinga/icinga2/pull/9095#issuecomment-974238004>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABA64C2VSFHYDMUP7ZJ2SQ3UMZ6EXANCNFSM5IMRJARA>.
> Triage notifications on the go with GitHub Mobile for iOS 
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> 
> or Android 
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
>
>

2021-11-22 13:27 UTC, lippserd commented
@cla-bot check

2021-11-29 10:44 UTC, Al2Klimov requested changes
Please explicitly `string()`ify what `macro()` returns to support numbers as well.

```
$ prefix/sbin/icinga2 console
Icinga 2 (version: v2.13.0-120-g9e3986698)
Type $help to view available commands.
<1> => "3"==3
false
<2> =>
```

2021-11-30 17:01 UTC, Al2Klimov commented
Around `macro()`, not next to.

2021-12-02 13:19 UTC, orbison commented
> Around `macro()`, not next to.
>
> https://icinga.com/docs/icinga-2/latest/doc/18-library-reference/#string

Incidentally, the documentation you are referring to suggests to use `.to_string()` instead of the global `string(...)` function.

However, I can see your point. `string(null)` is an empty string, but `null` does not provide a `.to_string()` method, so `macro().to_string()` would fail should the result of `macro()` become null. Right?

2021-12-02 14:22 UTC, Al2Klimov approved these changes

2021-12-02 14:23 UTC, Al2Klimov commented
Note: will have to be merged via squash-and-merge.

2021-12-07 14:29 UTC, merged