Worker process doesn't let parallel API package stage updates to complete when terminated
Icinga/icinga2 pull request #9326
Opened 2022-04-07 09:37 UTC by yhabteab

Backport of #9267

2022-04-07 09:55 UTC, Al2Klimov submitted a review, later dismissed

2022-04-07 11:03 UTC, Al2Klimov commented on lib/remote/configpackageutility.cpp
> +	});
This is fine, but strictly speaking you resolve merge conflicts like #9329.

2022-04-07 11:03 UTC, Al2Klimov commented on lib/remote/configpackageutility.cpp
> +	});
Just saying.

2022-04-07 12:26 UTC, julianbrost requested changes
Please take care of the compile errors.

2022-04-07 14:37 UTC, julianbrost requested changes

2022-04-08 10:28 UTC, julianbrost approved these changes

2022-04-08 10:28 UTC, merged