Add new option `-a` to the `mem` CheckCommand
Icinga/icinga2 pull request #9385
Opened 2022-06-01 18:44 UTC by cspeterson

It was recently added to the script:

https://github.com/justintime/nagios-plugins/commit/f4d96b5834154905819c6924b28a87a91e93a884

2022-06-02 07:21 UTC, bobapple commented
@cla-bot check

2022-06-02 12:14 UTC, cspeterson commented
signed ✍️

2022-06-07 06:50 UTC, julianbrost requested changes
Thank you for contributing to the project!

Can you please add the new option to the documentation at [`doc/10-icinga-template-library.md`](https://github.com/Icinga/icinga2/blob/master/doc/10-icinga-template-library.md#mem-) as well?

2022-06-09 07:49 UTC, julianbrost approved these changes

2022-06-22 10:51 UTC, Al2Klimov approved these changes

2022-06-22 10:52 UTC, merged