Run only a single job per workflow at a time
Icinga/icinga2 pull request #9424
Opened 2022-06-29 14:38 UTC by nilmerg

This limits each run of these workflows to a single action runner. This means, for each PR, merge or release only five runners run concurrently.

It also cancels pending jobs automatically, scoped to the workflow and pull request. Merge and release runs cannot cancel each other though.

We are limited to 20 runners concurrently. This means four PRs can still lock them up. But at least it prevents a single PR from locking up all resources.

At the moment it's only a draft, so feel free to ignore this at the moment. But I'd really like to merge this in the next days/weeks. (If it works as I thought, I'll cancel the runs after creating this PR so I can't tell if it does until all releases are finished)

2022-06-30 13:44 UTC, Al2Klimov reviewed
I doubt that’s acceptable.

2022-07-04 13:08 UTC, nilmerg commented
Nope, it does not. It seems to cancel it's own queue entries (╯°□°)╯︵ ┻━┻

2023-01-19 15:37 UTC, nilmerg commented
I got it working!!!!1 Please consider merging @julianbrost

2023-01-19 15:43 UTC, Al2Klimov commented
## TODO
* #9636
* [ ] rebase

2023-01-20 13:56 UTC, nilmerg commented
`group: deb-${{ github.ref }}` will be the final definition. Mine is then obsolete. It has the only change that master / tag runs don't get cancelled.

2023-01-20 14:00 UTC, Al2Klimov commented
A tag run? Gets cancelled? How?

2023-01-20 14:01 UTC, nilmerg commented
`github.ref` will also be a tag name, so subsequent pushes onto the same tag cancel the previous runs like on the master

2023-01-20 14:03 UTC, Al2Klimov commented
Only in this case they get cancelled? Then I consider that behaviour desired.

2023-01-20 14:20 UTC, julianbrost commented
So I'll have a closer look at #9636 and if it gets merged as-is, this PR will reduce down to adding `max-parallel: 1`?

2023-01-20 14:34 UTC, julianbrost requested changes
Okay, then it's time to do your rebasing :)

2023-01-20 14:48 UTC, Al2Klimov reviewed
LGTM, but... only 4/5?

2023-01-20 14:56 UTC, julianbrost approved these changes

2023-01-20 14:57 UTC, julianbrost commented
> LGTM, but... only 4/5?

Docker has no matrix and runs only one job anyways.

2023-01-20 15:04 UTC, Al2Klimov commented
Wait! One job **per PR**! #9636 already does this, but AFAIK OP's goals are beyond that.

2023-01-20 15:10 UTC, nilmerg commented
? My goals can be observed below :wink:

2023-01-20 15:15 UTC, julianbrost commented
#9636 limits to one workflow, this PR additionally limits to one job per workflow.

2023-01-20 15:15 UTC, Al2Klimov approved these changes

2023-01-20 19:35 UTC, merged