Require GCC 7+ for C++17
Icinga/icinga2 pull request #9485
Opened 2022-08-12 14:47 UTC by Al2Klimov

## Rationale

* more nice language features we can use instantly in features (and even in to be backported PRs as of Icinga... v2.15 I guess, security fixes – v2.16?)
* smaller (thus easier) range of compiler versions to support (just have a look at what our Web colleagues do)
* and – my fav. reason: because we can 😎

2022-08-16 08:20 UTC, Al2Klimov commented
## TODO

* [ ] #9489
* [ ] rebase
* [ ] push one-by-one, see what's actually required

2022-10-18 10:06 UTC, julianbrost requested changes
Why did you choose [that specific version from 2020 of nlohmann::json](https://github.com/nlohmann/json/releases/tag/v3.9.1)?

2022-10-18 10:54 UTC, Al2Klimov commented
See https://github.com/Icinga/icinga2/pull/9485/commits/8b1d3be117e1bd7faa0c3f459410538c9a4bd8a4 .

2023-03-31 12:06 UTC, julianbrost approved these changes

2023-03-31 12:06 UTC, merged