Move Types namespace into type.cpp and simplify Type::GetByName()
Icinga/icinga2 pull request #9608
Opened 2022-12-13 14:36 UTC by julianbrost

This PR moves the initialization of the `globals.Types` namespace to `type.cpp` in order to keep a pointer to the `Namespace` object in `Type::m_Namespace` and simplify `Type::GetByName()` using it.

The dynamic type check is moved into an assertion after freezing the namespace.

This PR is my suggested alternative to #9553 based on #9607. So far I haven't put too much effort into testing this, it's a idea/draft for now. All commits besides e2ca70d71316decfba0692ea584f8963348fa4ba are from the dependency.

### Blocked by
* #9607

2023-01-24 10:13 UTC, Al2Klimov requested changes
Do whatever is necessary to undraft it.

2023-01-24 10:17 UTC, julianbrost commented
Did you benchmark it? What were the results?

2023-01-24 10:40 UTC, Al2Klimov commented
1. Yes.
2. Not distinguishable.

2023-01-25 16:25 UTC, Al2Klimov commented on lib/base/scriptframe.cpp
> -	globalNS->Set("Types", l_TypesNS, true);
... from here?

2023-01-26 13:27 UTC, julianbrost commented on lib/base/type.cpp
> +	ScriptGlobal::GetGlobals()->Set("Types", l_TypesNS);
Unintentional, probably got lost in rebase/conflict resolution.

2023-01-26 14:06 UTC, Al2Klimov approved these changes

2023-01-26 17:32 UTC, merged