ITL: disk: set vars.disk_units="bytes"
Icinga/icinga2 pull request #9609
Opened 2022-12-13 16:26 UTC by Al2Klimov

so that check_disk doesn't output "MB" perfdata.
Those numbers actually represent MiB. Bytes don't have this problem.

2023-01-17 13:58 UTC, julianbrost requested changes
This also affects the check output, making it harder on read. I'd rather pass `-u MiB` as suggested in #9486 if this provides better compatibility while keeping the output more readable.

Also, my version of `check_disk` (monitoring-plugins 2.3.2) seems to always output the perfdata bytes. So with that version, this change makes things only worse.

2023-01-17 13:59 UTC, julianbrost commented
Also this wouldn't fix #9486, just work around it for a single plugin.

2023-01-18 12:40 UTC, Al2Klimov commented
Perfdata is already en-nice-ed by IW2. But for perfdata writers perfdata shall be precise. Glory to that plugin version.

2023-01-23 17:14 UTC, julianbrost commented
So what do we do with this? I think the best option would be one of leave as is (depend on being fixed in the plugins) or use `-u MiB`. Would be interesting to check what both options do with a few versions of monitoring-plugins and nagios-plugins. Can you please do so?

2023-01-25 16:00 UTC, Al2Klimov commented
Don't you agree with my last comment?

2023-01-26 08:54 UTC, julianbrost commented
Kind of, but it doesn't make a clear suggestion what to do with this PR. I'm guessing that might mean to just close the PR?

2023-01-26 14:00 UTC, Al2Klimov commented
No, just merge. It fixes the problem **and** does graphers a favor.

2023-01-26 14:19 UTC, julianbrost commented
https://github.com/Icinga/icinga2/pull/9609#pullrequestreview-1251603616:

> This also affects the check output, making it harder on read.

```console
$ /usr/lib/monitoring-plugins/check_disk -w 10% -c 5% -u bytes -p /tmp
DISK OK - free space: /tmp 15336124416B (92% inode=99%);| /tmp=1316564992B;14987420467;15820054937;0;16652689408
```

2023-01-26 14:35 UTC, Al2Klimov commented
https://github.com/Icinga/icinga2/pull/9609#issuecomment-1386993875:

Icinga Web 2 gives you nicer data and piecharts.

2023-01-26 15:07 UTC, Al2Klimov commented
Fedora 38, nagios-plugins-disk:

```
[root@b1f96b313185 /]# /usr/lib64/nagios/plugins/check_disk -w 1 -c 2
DISK OK - free space: / 38363 MiB (67.66% inode=83%); /dev 64 MiB (100.00% inode=100%); /dev/shm 64 MiB (100.00% inode=100%); /etc/resolv.conf 38363 MiB (67.66% inode=83%); /etc/hostname 38363 MiB (67.66% inode=83%); /etc/hosts 38363 MiB (67.66% inode=83%); /proc/acpi 2971 MiB (100.00% inode=100%); /proc/kcore 64 MiB (100.00% inode=100%); /proc/keys 64 MiB (100.00% inode=100%); /proc/timer_list 64 MiB (100.00% inode=100%); /sys/firmware 2971 MiB (100.00% inode=100%);| /=18336MiB;59766;59765;0;59767 /dev=0MiB;63;62;0;64 /dev/shm=0MiB;63;62;0;64 /etc/resolv.conf=18336MiB;59766;59765;0;59767 /etc/hostname=18336MiB;59766;59765;0;59767 /etc/hosts=18336MiB;59766;59765;0;59767 /proc/acpi=0MiB;2970;2969;0;2971 /proc/kcore=0MiB;63;62;0;64 /proc/keys=0MiB;63;62;0;64 /proc/timer_list=0MiB;63;62;0;64 /sys/firmware=0MiB;2970;2969;0;2971
[root@b1f96b313185 /]#
```

Ubuntu 23.04, monitoring-plugins:

```
root@511f75ff19ac:/# /usr/lib/nagios/plugins/check_disk -w 1 -c 2
DISK OK - free space: / 38363MiB (67% inode=82%); /etc/resolv.conf 38363MiB (67% inode=82%); /etc/hostname 38363MiB (67% inode=82%); /etc/hosts 38363MiB (67% inode=82%);| /=19226689536B;62669193216;62668144640;0;62670241792 /etc/resolv.conf=19226689536B;62669193216;62668144640;0;62670241792 /etc/hostname=19226689536B;62669193216;62668144640;0;62670241792 /etc/hosts=19226689536B;62669193216;62668144640;0;62670241792
root@511f75ff19ac:/#
```

IMAO both have fixed their problems.

2023-01-26 15:21 UTC, Al2Klimov commented
Shall we just drop our default -m? Both have sane defaults as shown above.

2023-01-26 15:50 UTC, julianbrost commented
New input: `check_disk` on Ubuntu 20.04 (monitoring-plugins 2.2) does not support `-u MiB`. So that's not an option.

> Shall we just drop our default -m?

Probably the best option as MB or MiB seems to always be the default anyways, it just sometimes breaks things (when it forces a version that knows and defaults to MiB back to SI unit MB).

2023-01-27 21:22 UTC, closed without merging