Fix ssl_cert deprecation warnings
Icinga/icinga2 pull request #9758
Opened 2023-05-08 14:40 UTC by OdyX

This addresses #9661

2023-05-08 14:54 UTC, bobapple commented
@cla-bot check

2023-05-17 13:52 UTC, Al2Klimov commented on itl/plugins-contrib.d/web.conf
> -			description = "Matches the pattern specified in -n with alternate"
What about passing --match here as well?

2023-05-17 13:57 UTC, Al2Klimov approved these changes

2023-07-14 08:27 UTC, Al2Klimov requested changes

2023-07-14 08:27 UTC, Al2Klimov commented on itl/plugins-contrib.d/web.conf
> -			description = "Matches the pattern specified in -n with alternate"
Please consider this one:

* https://github.com/liip-forks/icinga2/pull/1

You can merge it via rebase-and-merge not to produce an extra merge commit.

2023-07-25 11:56 UTC, Al2Klimov approved these changes

2024-05-24 09:57 UTC, merged

2025-10-17 13:56 UTC, jktr commented
I don't think setting `vars.ssl_cert_cn = "$ssl_cert_altnames$"` for compatibility works.

`check_ssl`'s `--altnames` (via `ssl_cert_altnames`) is a simple flag, but `--match` (via `ssl_cert_cn`) expects a pattern. So when the boolean `ssl_cert_altnames` is set but `ssl_cert_cn` isn't, `check_ssl` is called with `--match false` or `--match true`, which results in false negatives.

I've side-stepped this by setting `ssl_cert_cn` to a an actual pattern.

2025-10-20 08:30 UTC, yhabteab commented
Hi @jktr, and thanks for reporting!

That change indeed doesn't make any sense! Can you please submit a PR that reverts d3d74c237c54eed61d67600c2e04c3285a630189 or a new issue? This PR is merged and will quickly get lost!

2025-10-20 13:19 UTC, jktr commented
@yhabteab Thanks for confirming the problem. ~~I've opened a PR at https://github.com/Icinga/icinga2/pull/10611~~

edit: Due to the CCLA requirement, I won't be able to contribute a PR for this. I've opened an issue at https://github.com/Icinga/icinga2/issues/10615 instead to avoid this getting lost.

2025-10-20 14:33 UTC, OdyX commented
Good catch, thank you all for finding this out. I can't understand why past me proposed this without seeing the flag aspect, but here we are; I'm glad some more eyes landed on this issue!

2025-10-21 07:28 UTC, yhabteab commented
> I can't understand why past me proposed this without seeing the flag aspect, but here we are;

Hi, I don't think it's your fault :)! It's introduced by this https://github.com/liip-forks/icinga2/pull/1.