icinga2: address comment loading where host reference is not found
Icinga/icinga2 pull request #9861
Opened 2023-09-11 14:30 UTC by ymartin-ovh

address #9752: check if host reference is valid

2023-09-15 07:52 UTC, bobapple commented
@cla-bot check

2023-09-15 08:25 UTC, julianbrost commented
@Al2Klimov Please explain what #7786 has to do with this/what exactly this is supposed to fix here.

Anyways, `Comment::OnAllConfigLoaded()` even states in the validation error it can throw that it's supposed to handle non-existent hosts ("Comment '...' references a host/service which doesn't exist."), but apparently has a bug there, so that null check there should definitely by done.

2023-09-20 08:37 UTC, ymartin-ovh commented
Hello @julianbrost  / @Al2Klimov 

Should I rebase my diff with just null check in comment.cpp ?

Regards

2023-09-26 10:20 UTC, Al2Klimov requested changes
a27c6cf3d7debfdfd202c12f4f639d5227087961 is exactly what I wanted, **but** as a PR on its own **into** #7786. I.e. your new PR's spec:

* Base branch: bugfix/api-runtime-object-sync-order (not master)
* Commits: a27c6cf3d7debfdfd202c12f4f639d5227087961
* Also mention me there once done

2023-09-26 11:56 UTC, ymartin-ovh commented
Hello @Al2Klimov 

I can do that but the commit you want does not address the bug I submitted.
We have to deal with the null reference use.

Regards

2023-10-06 12:46 UTC, ymartin-ovh commented
I rollback to my original contribution about null reference check.

2023-10-09 15:33 UTC, Al2Klimov submitted a review, later dismissed
> that null check there should definitely by done

– https://github.com/Icinga/icinga2/pull/9861#issuecomment-1720879979

I agree.

2024-11-13 13:46 UTC, ymartin-ovh commented
Hello

Do you plan to integrate this fix in 2.14.x branch too ? We have this issue in 2.14, I maintain my own build because of this.

Regards

2024-11-14 09:28 UTC, Al2Klimov approved these changes

2025-01-07 12:39 UTC, Al2Klimov commented on lib/icinga/comment.cpp
>  		m_Checkable = host->GetServiceByShortName(GetServiceName());
* Colleagues, wanna get this little thing done, so that OP can test #9752 with snapshot packages?

2025-01-07 13:04 UTC, julianbrost commented on lib/icinga/comment.cpp
>  		m_Checkable = host->GetServiceByShortName(GetServiceName());
https://github.com/Icinga/icinga2/pull/9861#issuecomment-2473668998:

> I maintain my own build because of this.

Sounds like it should already be tested?

2025-01-07 13:12 UTC, merged

2025-01-07 13:44 UTC, Al2Klimov commented
* Sorry, of course you're right – this PR is nice, but #10000 _should_ do the thing by itself.