Docs: change "Amazon Linux 2" to "Amazon Linux" where applicable
Icinga/icinga2 pull request #9864
Opened 2023-09-27 15:48 UTC by Al2Klimov

We also support Amazon Linux 2023 now.

2023-10-25 13:05 UTC, julianbrost requested changes
There's more to do here than just remove the version number. https://icinga.com/docs/icinga-2/latest/doc/02-installation/09-Amazon-Linux/ mentions EPEL, which isn't available on Amazon Linux 2023, so this will also need some case distinctions depending on the version.

2023-11-02 14:09 UTC, julianbrost requested changes
I mean this PR is great if you want to do the minimal change so that the result is technically correct, but it would be nicer if places were clearly labelled which versions they apply to (I think the [RHEL instructions](https://icinga.com/docs/icinga-2/latest/doc/02-installation/06-RHEL/) are a good example in this regards). So at least the wording should be changed where it actually only applies to Amazon Linux to make it clear that there's actually nothing to do on newer version.

2023-11-06 16:37 UTC, Al2Klimov commented
That wasn't my motivation. I mean, sure I can tell more explicitly that only v2 needs EPEL for Boost. The users will thank me for not having to search for the non-existing EPEL for AL2023.

But what to do with the other one, the `yum install nagios-plugins-all` part? I'd like not to talk about https://github.com/amazonlinux/amazon-linux-2023/issues/367 not to awake sleeping dogs. I mean, c'mon. How awkward is this? We've packaged Icinga 2 for subscription on a distro w/o even Nagios plugins! 🙈

2023-11-21 10:09 UTC, julianbrost approved these changes

2023-11-21 10:09 UTC, merged