GHA: complain if PR adds commits from people not yet listed in ./AUTHORS
Icinga/icinga2 pull request #9911
Opened 2023-11-20 14:44 UTC by Al2Klimov

not to have to update ./AUTHORS or .mailmap after merging.

This substitutes ProBot functionality.

2023-11-20 15:10 UTC, Al2Klimov commented
Not critically necessary, but should prevent stuff like https://github.com/Icinga/icinga2/pull/9697#discussion_r1108689704.

2023-11-21 11:29 UTC, julianbrost requested changes

2023-11-21 11:29 UTC, julianbrost commented on .github/workflows/authors-file.yml
> +        run: .github/workflows/authors-file.bash
If you click on [details](https://github.com/Icinga/icinga2/actions/runs/6933055461/job/18858366742?pr=9911) for the failing job of this PR, the output is trying to be helpful but the helpful part is hidden somewhere in the middle.

So I'd either remove the debug output, or split this job into two parts: one that always succeeds and writes the helpful message in a file if there's a problem, and then a second job that outputs that file and fails if it exists/is non-empty.

2023-11-21 12:47 UTC, julianbrost reviewed
Looks fine in the failing case, please remove the second commit so that we can also see it working if everything is fine.

2023-11-21 15:38 UTC, julianbrost approved these changes

2023-11-23 11:38 UTC, merged